// Code generated by agentflow v0.4.2; DO NOT EDIT.

package chatagent2

import (
	"strconv"
	"strings"
)

type SystemPrompt struct {
	AiName string
}

func (input *SystemPrompt) String() string {
	var b strings.Builder
	length := 0
	length += 35
	length += len(input.AiName)
	length += 280
	b.Grow(length)
	b.WriteString("You are a friendly assistant named ")
	b.WriteString(input.AiName)
	b.WriteString(" who can help users with their questions.\nDo not hallucinate. Do not lie. Do not be rude. Do not be inappropriate.\nIf you do not know the answer to a question, please say so.\n2 newlines will produce a newline in the output at the end of the prompt.\nThis prompt uses the technique.")
	return b.String()
}

type CreateTitle struct {
	UserName      string
	MessageThread string
}

func (input *CreateTitle) String() string {
	var b strings.Builder
	length := 0
	length += 62
	length += len(input.UserName)
	length += 2
	length += len(input.MessageThread)
	length += 7
	b.Grow(length)
	b.WriteString("Create a title summarizing the contents of this exchange with ")
	b.WriteString(input.UserName)
	b.WriteString(":\n")
	b.WriteString(input.MessageThread)
	b.WriteString("\ntitle:")
	return b.String()
}

type ChatWithUser struct {
	AiName        string
	MessageThread string
}

func (input *ChatWithUser) String() string {
	var b strings.Builder
	length := 0
	length += 20
	length += len(input.AiName)
	length += 43
	length += len(input.MessageThread)
	length += 1
	length += len(input.AiName)
	length += 1
	b.Grow(length)
	b.WriteString("You are an AI named ")
	b.WriteString(input.AiName)
	b.WriteString(". Please respond to the chat thread below:\n")
	b.WriteString(input.MessageThread)
	b.WriteRune('\n')
	b.WriteString(input.AiName)
	b.WriteString(":")
	return b.String()
}

type ExampleWithManyVariables struct {
	UserName      string
	MessageThread string
	AiName        string
	Title         string
	MaxLineLen    string
	MoreVariables string
}

func (input *ExampleWithManyVariables) String() string {
	var b strings.Builder
	length := 0
	length += len(input.UserName)
	length += 1
	length += len(input.MessageThread)
	length += 1
	length += len(input.AiName)
	length += 1
	length += len(input.Title)
	length += 32
	length += len(input.UserName)
	length += 15
	length += len(input.AiName)
	length += 64
	length += len(input.MaxLineLen)
	length += 13
	length += len(input.MoreVariables)
	length += 151
	b.Grow(length)
	b.WriteString(input.UserName)
	b.WriteRune('\n')
	b.WriteString(input.MessageThread)
	b.WriteRune('\n')
	b.WriteString(input.AiName)
	b.WriteRune('\n')
	b.WriteString(input.Title)
	b.WriteString("\nAs the title says, the user is ")
	b.WriteString(input.UserName)
	b.WriteString(" and the AI is ")
	b.WriteString(input.AiName)
	b.WriteString(".\nThe default max line length is 80 characters. It is currently ")
	b.WriteString(input.MaxLineLen)
	b.WriteString(".\nSometimes, ")
	b.WriteString(input.MoreVariables)
	b.WriteString(" are needed.\nWhen the max line length is surpassed, AgentFlow will wrap the line.\nThis only applies to function headers. Prompt bodies are not wrapped.")
	return b.String()
}

type ConditionalPrompting struct {
	User struct {
		Email string
	}
}

func (input *ConditionalPrompting) isUserZero() bool {
	return input.User.Email == ""
}

func (input *ConditionalPrompting) String() string {
	var b strings.Builder
	length := 0
	length += 64
	if input.User.Email != "" {
		length += 21
		length += len(input.User.Email)
		length += 2
	}
	b.Grow(length)
	b.WriteString("This prompt demonstrates conditional prompting using optionals.\n")
	if input.User.Email != "" {
		b.WriteString("\nThe user's email is ")
		b.WriteString(input.User.Email)
		b.WriteString(".\n")
	}
	return b.String()
}

type ConditionalWithElse struct {
	User struct {
		Premium      bool
		Subscription struct {
			Tier int
		}
	}
}

func (input *ConditionalWithElse) isUserZero() bool {
	return !input.User.Premium &&
		input.isUserSubscriptionZero()
}

func (input *ConditionalWithElse) isUserSubscriptionZero() bool {
	return input.User.Subscription.Tier == 0
}

func (input *ConditionalWithElse) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.User.Subscription.Tier)
	length := 0
	length += 36
	if input.User.Premium {
		length += 88
		length += len(var0)
		length += 34
		length += len(var0)
		length += 2
	} else {
		length += 80
	}
	b.Grow(length)
	b.WriteString("Here's an example with else syntax:\n")
	if input.User.Premium {
		b.WriteString("\nWelcome premium user! You have access to all features.\nYour subscription tier is level ")
		b.WriteString(var0)
		b.WriteString(".\nOnce again, that tier number is ")
		b.WriteString(var0)
		b.WriteString(".\n")
	} else {
		b.WriteString("\nWelcome! You're using the basic version. Upgrade to premium for more features.\n")
	}
	return b.String()
}
