// Code generated by agentflow v0.5.3; DO NOT EDIT.

package creativewriting

import (
	"strconv"
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return "You are CreativeWriter Pro, a versatile AI writing assistant specializing in storytelling, creative fiction, and narrative development. You adapt your style and guidance based on genre, target audience, and the writer's experience level."
}

type WritingSessionIntroduction struct {
	Writer struct {
		Name           string
		Experience     string
		FavoriteGenres string
		CurrentStreak  int
	}
	Session struct {
		Goal        string
		TargetWords int
	}
	Project struct {
		Title                string
		Genre                string
		Audience             string
		CurrentWords         int
		CompletionPercentage int
	}
}

func (input *WritingSessionIntroduction) isWriterZero() bool {
	return input.Writer.Name == "" &&
		input.Writer.Experience == "" &&
		input.Writer.FavoriteGenres == "" &&
		input.Writer.CurrentStreak == 0
}

func (input *WritingSessionIntroduction) isSessionZero() bool {
	return input.Session.Goal == "" &&
		input.Session.TargetWords == 0
}

func (input *WritingSessionIntroduction) isProjectZero() bool {
	return input.Project.Title == "" &&
		input.Project.Genre == "" &&
		input.Project.Audience == "" &&
		input.Project.CurrentWords == 0 &&
		input.Project.CompletionPercentage == 0
}

func (input *WritingSessionIntroduction) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Session.TargetWords)
	var1 := strconv.Itoa(input.Writer.CurrentStreak)
	var2 := strconv.Itoa(input.Project.CurrentWords)
	var3 := strconv.Itoa(input.Project.CompletionPercentage)
	length := 0
	length += 49
	length += len(input.Writer.Name)
	length += 84
	length += len(input.Writer.Experience)
	length += 25
	length += len(input.Writer.FavoriteGenres)
	length += 21
	length += len(input.Session.Goal)
	length += 26
	length += len(var0)
	length += 8
	if input.Writer.CurrentStreak != 0 {
		length += 26
		length += len(var1)
		length += 20
		if input.Writer.CurrentStreak >= 30 {
			length += 67
		}
		length += 37
		length += len(input.Project.Title)
		length += 12
		length += len(input.Project.Genre)
		length += 22
		length += len(input.Project.Audience)
		length += 21
		length += len(var2)
		length += 8
		if input.Project.CompletionPercentage != 0 {
			length += 15
			length += len(var3)
			length += 12
			if input.Project.CompletionPercentage >= 75 {
				length += 53
			}
			length += 2
			if input.Project.CompletionPercentage < 25 {
				length += 65
			}
			length += 1
		}
	}
	b.Grow(length)
	b.WriteString("# ✍️ Creative Writing Session\n\nWelcome back, ")
	b.WriteString(input.Writer.Name)
	b.WriteString("! Let's bring your stories to life.\n\n## 👤 Writer Profile\n- **Experience Level**: ")
	b.WriteString(input.Writer.Experience)
	b.WriteString("\n- **Preferred Genres**: ")
	b.WriteString(input.Writer.FavoriteGenres)
	b.WriteString("\n- **Writing Goal**: ")
	b.WriteString(input.Session.Goal)
	b.WriteString("\n- **Target Word Count**: ")
	b.WriteString(var0)
	b.WriteString(" words\n\n")
	if input.Writer.CurrentStreak != 0 {
		b.WriteString("\n🔥 **Writing Streak**: ")
		b.WriteString(var1)
		b.WriteString(" days! Keep it up!\n\n")
		if input.Writer.CurrentStreak >= 30 {
			b.WriteString("\n🏆 **Master Writer**: 30+ day streak! You're a writing machine!\n")
		}
		b.WriteString("\n\n## 📖 Current Project\n**Title**: ")
		b.WriteString(input.Project.Title)
		b.WriteString("\n**Genre**: ")
		b.WriteString(input.Project.Genre)
		b.WriteString("\n**Target Audience**: ")
		b.WriteString(input.Project.Audience)
		b.WriteString("\n**Current Length**: ")
		b.WriteString(var2)
		b.WriteString(" words\n\n")
		if input.Project.CompletionPercentage != 0 {
			b.WriteString("\n**Progress**: ")
			b.WriteString(var3)
			b.WriteString("% complete\n\n")
			if input.Project.CompletionPercentage >= 75 {
				b.WriteString("\n🎉 **Almost there!** You're in the final stretch!\n")
			}
			b.WriteString("\n\n")
			if input.Project.CompletionPercentage < 25 {
				b.WriteString("\n🌱 **Just getting started** - The hardest part is behind you!\n")
			}
			b.WriteRune('\n')
		}
	}
	return b.String()
}

type GenreSpecificGuidance struct {
	Project struct {
		Genre string
	}
	Fantasy struct {
		WorldComplexity   string
		MagicSystem       string
		TimePeriod        string
		Creatures         string
		Locations         string
		Conflicts         string
		HasMagicRules     bool
		MagicRules        string
		MagicLimitations  string
		MagicConsequences string
	}
	Scifi struct {
		Subgenre        string
		TechnologyLevel string
		Setting         string
		Technologies    string
		ScienceFocus    string
		Themes          string
		HasTimeTravel   bool
		TimeTravelType  string
		TimeTravelRules string
		ParadoxApproach string
	}
	Mystery struct {
		Type            string
		ProtagonistType string
		CrimeType       string
		ClueCount       int
		TotalClues      int
		RedHerrings     int
		SuspectCount    int
		RemainingClues  int
		Suspect1        string
		Motive1         string
		Suspect2        string
		Motive2         string
		Suspect3        string
		Motive3         string
	}
	Romance struct {
		Subgenre           string
		HeatLevel          string
		MainTrope          string
		ProtagonistName    string
		LoveInterestName   string
		MeetCute           string
		ConflictType       string
		ConflictSource     string
		ResolutionApproach string
	}
}

func (input *GenreSpecificGuidance) isProjectZero() bool {
	return input.Project.Genre == ""
}

func (input *GenreSpecificGuidance) isFantasyZero() bool {
	return input.Fantasy.WorldComplexity == "" &&
		input.Fantasy.MagicSystem == "" &&
		input.Fantasy.TimePeriod == "" &&
		input.Fantasy.Creatures == "" &&
		input.Fantasy.Locations == "" &&
		input.Fantasy.Conflicts == "" &&
		!input.Fantasy.HasMagicRules &&
		input.Fantasy.MagicRules == "" &&
		input.Fantasy.MagicLimitations == "" &&
		input.Fantasy.MagicConsequences == ""
}

func (input *GenreSpecificGuidance) isScifiZero() bool {
	return input.Scifi.Subgenre == "" &&
		input.Scifi.TechnologyLevel == "" &&
		input.Scifi.Setting == "" &&
		input.Scifi.Technologies == "" &&
		input.Scifi.ScienceFocus == "" &&
		input.Scifi.Themes == "" &&
		!input.Scifi.HasTimeTravel &&
		input.Scifi.TimeTravelType == "" &&
		input.Scifi.TimeTravelRules == "" &&
		input.Scifi.ParadoxApproach == ""
}

func (input *GenreSpecificGuidance) isMysteryZero() bool {
	return input.Mystery.Type == "" &&
		input.Mystery.ProtagonistType == "" &&
		input.Mystery.CrimeType == "" &&
		input.Mystery.ClueCount == 0 &&
		input.Mystery.TotalClues == 0 &&
		input.Mystery.RedHerrings == 0 &&
		input.Mystery.SuspectCount == 0 &&
		input.Mystery.RemainingClues == 0 &&
		input.Mystery.Suspect1 == "" &&
		input.Mystery.Motive1 == "" &&
		input.Mystery.Suspect2 == "" &&
		input.Mystery.Motive2 == "" &&
		input.Mystery.Suspect3 == "" &&
		input.Mystery.Motive3 == ""
}

func (input *GenreSpecificGuidance) isRomanceZero() bool {
	return input.Romance.Subgenre == "" &&
		input.Romance.HeatLevel == "" &&
		input.Romance.MainTrope == "" &&
		input.Romance.ProtagonistName == "" &&
		input.Romance.LoveInterestName == "" &&
		input.Romance.MeetCute == "" &&
		input.Romance.ConflictType == "" &&
		input.Romance.ConflictSource == "" &&
		input.Romance.ResolutionApproach == ""
}

func (input *GenreSpecificGuidance) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Mystery.ClueCount)
	var1 := strconv.Itoa(input.Mystery.TotalClues)
	var2 := strconv.Itoa(input.Mystery.RedHerrings)
	var3 := strconv.Itoa(input.Mystery.SuspectCount)
	var4 := strconv.Itoa(input.Mystery.RemainingClues)
	length := 0
	if input.Project.Genre == "fantasy" {
		length += 66
		length += len(input.Fantasy.WorldComplexity)
		length += 19
		length += len(input.Fantasy.MagicSystem)
		length += 18
		length += len(input.Fantasy.TimePeriod)
		length += 51
		length += len(input.Fantasy.Creatures)
		length += 18
		length += len(input.Fantasy.Locations)
		length += 18
		length += len(input.Fantasy.Conflicts)
		length += 2
		if input.Fantasy.HasMagicRules {
			length += 28
			length += len(input.Fantasy.MagicRules)
			length += 25
			length += len(input.Fantasy.MagicLimitations)
			length += 19
			length += len(input.Fantasy.MagicConsequences)
			length += 1
		}
		length += 150
	}
	length += 2
	if input.Project.Genre == "sci-fi" {
		length += 54
		length += len(input.Scifi.Subgenre)
		length += 17
		length += len(input.Scifi.TechnologyLevel)
		length += 14
		length += len(input.Scifi.Setting)
		length += 41
		length += len(input.Scifi.Technologies)
		length += 28
		length += len(input.Scifi.ScienceFocus)
		length += 22
		length += len(input.Scifi.Themes)
		length += 2
		if input.Scifi.HasTimeTravel {
			length += 41
			length += len(input.Scifi.TimeTravelType)
			length += 12
			length += len(input.Scifi.TimeTravelRules)
			length += 23
			length += len(input.Scifi.ParadoxApproach)
			length += 1
		}
		length += 138
	}
	length += 2
	if input.Project.Genre == "mystery" {
		length += 49
		length += len(input.Mystery.Type)
		length += 16
		length += len(input.Mystery.ProtagonistType)
		length += 12
		length += len(input.Mystery.CrimeType)
		length += 46
		length += len(var0)
		length += 1
		length += len(var1)
		length += 21
		length += len(var2)
		length += 17
		length += len(var3)
		length += 2
		if input.Mystery.ClueCount < input.Mystery.TotalClues {
			length += 48
			length += len(var4)
			length += 13
		}
		length += 27
		length += len(input.Mystery.Suspect1)
		length += 11
		length += len(input.Mystery.Motive1)
		length += 4
		length += len(input.Mystery.Suspect2)
		length += 11
		length += len(input.Mystery.Motive2)
		length += 4
		length += len(input.Mystery.Suspect3)
		length += 11
		length += len(input.Mystery.Motive3)
		length += 130
	}
	length += 2
	if input.Project.Genre == "romance" {
		length += 49
		length += len(input.Romance.Subgenre)
		length += 17
		length += len(input.Romance.HeatLevel)
		length += 12
		length += len(input.Romance.MainTrope)
		length += 48
		length += len(input.Romance.ProtagonistName)
		length += 22
		length += len(input.Romance.LoveInterestName)
		length += 18
		length += len(input.Romance.MeetCute)
		length += 2
		if input.Romance.ConflictType != "" {
			length += 32
			length += len(input.Romance.ConflictType)
			length += 13
			length += len(input.Romance.ConflictSource)
			length += 26
			length += len(input.Romance.ResolutionApproach)
			length += 1
		}
		length += 132
	}
	b.Grow(length)
	if input.Project.Genre == "fantasy" {
		b.WriteString("\n## 🧙‍♂️ Fantasy Writing Mode\n\n**World-Building Focus**: ")
		b.WriteString(input.Fantasy.WorldComplexity)
		b.WriteString("\n**Magic System**: ")
		b.WriteString(input.Fantasy.MagicSystem)
		b.WriteString("\n**Setting Era**: ")
		b.WriteString(input.Fantasy.TimePeriod)
		b.WriteString("\n\n### Fantasy Elements Checklist:\n- **Creatures**: ")
		b.WriteString(input.Fantasy.Creatures)
		b.WriteString("\n- **Locations**: ")
		b.WriteString(input.Fantasy.Locations)
		b.WriteString("\n- **Conflicts**: ")
		b.WriteString(input.Fantasy.Conflicts)
		b.WriteString("\n\n")
		if input.Fantasy.HasMagicRules {
			b.WriteString("\n### ⚡ Magic System Rules\n")
			b.WriteString(input.Fantasy.MagicRules)
			b.WriteString("\n\n**Power Limitations**: ")
			b.WriteString(input.Fantasy.MagicLimitations)
			b.WriteString("\n**Consequences**: ")
			b.WriteString(input.Fantasy.MagicConsequences)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n**Writing Tip**: In fantasy, consistency in world-building is key. Make sure your magic system and world rules stay coherent throughout your story.\n")
	}
	b.WriteString("\n\n")
	if input.Project.Genre == "sci-fi" {
		b.WriteString("\n## 🚀 Science Fiction Writing Mode\n\n**Sub-genre**: ")
		b.WriteString(input.Scifi.Subgenre)
		b.WriteString("\n**Tech Level**: ")
		b.WriteString(input.Scifi.TechnologyLevel)
		b.WriteString("\n**Setting**: ")
		b.WriteString(input.Scifi.Setting)
		b.WriteString("\n\n### Sci-Fi Elements:\n- **Technology**: ")
		b.WriteString(input.Scifi.Technologies)
		b.WriteString("\n- **Scientific Concepts**: ")
		b.WriteString(input.Scifi.ScienceFocus)
		b.WriteString("\n- **Social Issues**: ")
		b.WriteString(input.Scifi.Themes)
		b.WriteString("\n\n")
		if input.Scifi.HasTimeTravel {
			b.WriteString("\n### ⏰ Time Travel Mechanics\n**Type**: ")
			b.WriteString(input.Scifi.TimeTravelType)
			b.WriteString("\n**Rules**: ")
			b.WriteString(input.Scifi.TimeTravelRules)
			b.WriteString("\n**Paradox Handling**: ")
			b.WriteString(input.Scifi.ParadoxApproach)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n**Writing Tip**: Great sci-fi isn't just about the technology—it's about how that technology affects human relationships and society.\n")
	}
	b.WriteString("\n\n")
	if input.Project.Genre == "mystery" {
		b.WriteString("\n## 🔍 Mystery Writing Mode\n\n**Mystery Type**: ")
		b.WriteString(input.Mystery.Type)
		b.WriteString("\n**Detective**: ")
		b.WriteString(input.Mystery.ProtagonistType)
		b.WriteString("\n**Crime**: ")
		b.WriteString(input.Mystery.CrimeType)
		b.WriteString("\n\n### Mystery Structure:\n- **Clues Planted**: ")
		b.WriteString(var0)
		b.WriteString("/")
		b.WriteString(var1)
		b.WriteString("\n- **Red Herrings**: ")
		b.WriteString(var2)
		b.WriteString("\n- **Suspects**: ")
		b.WriteString(var3)
		b.WriteString("\n\n")
		if input.Mystery.ClueCount < input.Mystery.TotalClues {
			b.WriteString("\n⚠️ **Clue Alert**: You still need to plant ")
			b.WriteString(var4)
			b.WriteString(" more clues!\n")
		}
		b.WriteString("\n\n### Current Suspects:\n1. ")
		b.WriteString(input.Mystery.Suspect1)
		b.WriteString(" - Motive: ")
		b.WriteString(input.Mystery.Motive1)
		b.WriteString("\n2. ")
		b.WriteString(input.Mystery.Suspect2)
		b.WriteString(" - Motive: ")
		b.WriteString(input.Mystery.Motive2)
		b.WriteString("\n3. ")
		b.WriteString(input.Mystery.Suspect3)
		b.WriteString(" - Motive: ")
		b.WriteString(input.Mystery.Motive3)
		b.WriteString("\n\n**Writing Tip**: Play fair with your readers—give them all the clues they need to solve the mystery alongside your detective.\n")
	}
	b.WriteString("\n\n")
	if input.Project.Genre == "romance" {
		b.WriteString("\n## 💕 Romance Writing Mode\n\n**Romance Type**: ")
		b.WriteString(input.Romance.Subgenre)
		b.WriteString("\n**Heat Level**: ")
		b.WriteString(input.Romance.HeatLevel)
		b.WriteString("\n**Trope**: ")
		b.WriteString(input.Romance.MainTrope)
		b.WriteString("\n\n### Character Development:\n- **Protagonist**: ")
		b.WriteString(input.Romance.ProtagonistName)
		b.WriteString("\n- **Love Interest**: ")
		b.WriteString(input.Romance.LoveInterestName)
		b.WriteString("\n- **Meet-Cute**: ")
		b.WriteString(input.Romance.MeetCute)
		b.WriteString("\n\n")
		if input.Romance.ConflictType != "" {
			b.WriteString("\n### Central Conflict\n**Type**: ")
			b.WriteString(input.Romance.ConflictType)
			b.WriteString("\n**Source**: ")
			b.WriteString(input.Romance.ConflictSource)
			b.WriteString("\n**Resolution Strategy**: ")
			b.WriteString(input.Romance.ResolutionApproach)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n**Writing Tip**: Great romance is built on emotional truth. Make sure both characters grow and change through their relationship.\n")
	}
	return b.String()
}

type CharacterDevelopmentWorkshop struct {
	Characters struct {
		MainCharacter struct {
			Name              string
			Archetype         string
			Flaw              string
			Desire            string
			Arc               string
			BackstoryComplete bool
			NeedsDevelopment  bool
			WeakAreas         string
		}
		Antagonist struct {
			Name          string
			Type          string
			Motivation    string
			Methods       string
			Sympathetic   bool
			ConflictStyle string
		}
		SupportingCast int
		Support1       struct {
			Name string
			Role string
		}
		Support2 struct {
			Name string
			Role string
		}
		Support3 struct {
			Name string
			Role string
		}
	}
}

func (input *CharacterDevelopmentWorkshop) isCharactersZero() bool {
	return input.isCharactersMainCharacterZero() &&
		input.isCharactersAntagonistZero() &&
		input.Characters.SupportingCast == 0 &&
		input.isCharactersSupport1Zero() &&
		input.isCharactersSupport2Zero() &&
		input.isCharactersSupport3Zero()
}

func (input *CharacterDevelopmentWorkshop) isCharactersMainCharacterZero() bool {
	return input.Characters.MainCharacter.Name == "" &&
		input.Characters.MainCharacter.Archetype == "" &&
		input.Characters.MainCharacter.Flaw == "" &&
		input.Characters.MainCharacter.Desire == "" &&
		input.Characters.MainCharacter.Arc == "" &&
		!input.Characters.MainCharacter.BackstoryComplete &&
		!input.Characters.MainCharacter.NeedsDevelopment &&
		input.Characters.MainCharacter.WeakAreas == ""
}

func (input *CharacterDevelopmentWorkshop) isCharactersAntagonistZero() bool {
	return input.Characters.Antagonist.Name == "" &&
		input.Characters.Antagonist.Type == "" &&
		input.Characters.Antagonist.Motivation == "" &&
		input.Characters.Antagonist.Methods == "" &&
		!input.Characters.Antagonist.Sympathetic &&
		input.Characters.Antagonist.ConflictStyle == ""
}

func (input *CharacterDevelopmentWorkshop) isCharactersSupport1Zero() bool {
	return input.Characters.Support1.Name == "" &&
		input.Characters.Support1.Role == ""
}

func (input *CharacterDevelopmentWorkshop) isCharactersSupport2Zero() bool {
	return input.Characters.Support2.Name == "" &&
		input.Characters.Support2.Role == ""
}

func (input *CharacterDevelopmentWorkshop) isCharactersSupport3Zero() bool {
	return input.Characters.Support3.Name == "" &&
		input.Characters.Support3.Role == ""
}

func (input *CharacterDevelopmentWorkshop) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Characters.SupportingCast)
	length := 0
	length += 28
	if !input.isCharactersMainCharacterZero() {
		length += 18
		length += len(input.Characters.MainCharacter.Name)
		length += 17
		length += len(input.Characters.MainCharacter.Archetype)
		length += 17
		length += len(input.Characters.MainCharacter.Flaw)
		length += 21
		length += len(input.Characters.MainCharacter.Desire)
		length += 17
		length += len(input.Characters.MainCharacter.Arc)
		length += 2
		if input.Characters.MainCharacter.BackstoryComplete {
			length += 55
		}
		length += 2
		if input.Characters.MainCharacter.NeedsDevelopment {
			length += 61
			length += len(input.Characters.MainCharacter.WeakAreas)
			length += 1
		}
		length += 1
	}
	length += 2
	if !input.isCharactersAntagonistZero() {
		length += 17
		length += len(input.Characters.Antagonist.Name)
		length += 12
		length += len(input.Characters.Antagonist.Type)
		length += 17
		length += len(input.Characters.Antagonist.Motivation)
		length += 14
		length += len(input.Characters.Antagonist.Methods)
		length += 2
		if input.Characters.Antagonist.Sympathetic {
			length += 92
		}
		length += 22
		length += len(input.Characters.Antagonist.ConflictStyle)
		length += 1
	}
	length += 2
	if input.Characters.SupportingCast != 0 {
		length += 28
		length += len(var0)
		length += 9
		if input.Characters.SupportingCast > 5 {
			length += 109
		}
		length += 30
		length += len(input.Characters.Support1.Name)
		length += 2
		length += len(input.Characters.Support1.Role)
		length += 3
		length += len(input.Characters.Support2.Name)
		length += 2
		length += len(input.Characters.Support2.Role)
		length += 3
		length += len(input.Characters.Support3.Name)
		length += 2
		length += len(input.Characters.Support3.Role)
		length += 1
	}
	b.Grow(length)
	b.WriteString("## 👥 Character Analysis\n\n")
	if !input.isCharactersMainCharacterZero() {
		b.WriteString("\n### Protagonist: ")
		b.WriteString(input.Characters.MainCharacter.Name)
		b.WriteString("\n\n**Archetype**: ")
		b.WriteString(input.Characters.MainCharacter.Archetype)
		b.WriteString("\n**Fatal Flaw**: ")
		b.WriteString(input.Characters.MainCharacter.Flaw)
		b.WriteString("\n**Deepest Desire**: ")
		b.WriteString(input.Characters.MainCharacter.Desire)
		b.WriteString("\n**Growth Arc**: ")
		b.WriteString(input.Characters.MainCharacter.Arc)
		b.WriteString("\n\n")
		if input.Characters.MainCharacter.BackstoryComplete {
			b.WriteString("\n✅ **Backstory Complete**: Well-developed background\n")
		}
		b.WriteString("\n\n")
		if input.Characters.MainCharacter.NeedsDevelopment {
			b.WriteString("\n🔧 **Development Needed**: Character needs more depth in: ")
			b.WriteString(input.Characters.MainCharacter.WeakAreas)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if !input.isCharactersAntagonistZero() {
		b.WriteString("\n### Antagonist: ")
		b.WriteString(input.Characters.Antagonist.Name)
		b.WriteString("\n\n**Type**: ")
		b.WriteString(input.Characters.Antagonist.Type)
		b.WriteString("\n**Motivation**: ")
		b.WriteString(input.Characters.Antagonist.Motivation)
		b.WriteString("\n**Methods**: ")
		b.WriteString(input.Characters.Antagonist.Methods)
		b.WriteString("\n\n")
		if input.Characters.Antagonist.Sympathetic {
			b.WriteString("\n💡 **Sympathetic Villain**: Your antagonist has relatable motivations - this adds depth!\n")
		}
		b.WriteString("\n\n**Conflict Style**: ")
		b.WriteString(input.Characters.Antagonist.ConflictStyle)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Characters.SupportingCast != 0 {
		b.WriteString("\n### Supporting Characters (")
		b.WriteString(var0)
		b.WriteString(" total)\n\n")
		if input.Characters.SupportingCast > 5 {
			b.WriteString("\n⚠️ **Character Overload**: You have many supporting characters. Make sure each serves a unique purpose!\n")
		}
		b.WriteString("\n\n**Key Supporting Roles**:\n- ")
		b.WriteString(input.Characters.Support1.Name)
		b.WriteString(": ")
		b.WriteString(input.Characters.Support1.Role)
		b.WriteString("\n- ")
		b.WriteString(input.Characters.Support2.Name)
		b.WriteString(": ")
		b.WriteString(input.Characters.Support2.Role)
		b.WriteString("\n- ")
		b.WriteString(input.Characters.Support3.Name)
		b.WriteString(": ")
		b.WriteString(input.Characters.Support3.Role)
		b.WriteRune('\n')
	}
	return b.String()
}

type PlotStructureAnalysis struct {
	Plot struct {
		StructureType    string
		CurrentAct       int
		TotalActs        int
		IncitingIncident bool
		FirstPlotPoint   bool
		Midpoint         bool
		Climax           bool
		Resolution       bool
		Pacing           string
		TensionLevel     int
	}
	Scene struct {
		Description   string
		Purpose       string
		PovCharacter  string
		Location      string
		PlotGoal      string
		CharacterGoal string
		EmotionalGoal string
		HasConflict   bool
		ConflictType  string
	}
}

func (input *PlotStructureAnalysis) isPlotZero() bool {
	return input.Plot.StructureType == "" &&
		input.Plot.CurrentAct == 0 &&
		input.Plot.TotalActs == 0 &&
		!input.Plot.IncitingIncident &&
		!input.Plot.FirstPlotPoint &&
		!input.Plot.Midpoint &&
		!input.Plot.Climax &&
		!input.Plot.Resolution &&
		input.Plot.Pacing == "" &&
		input.Plot.TensionLevel == 0
}

func (input *PlotStructureAnalysis) isSceneZero() bool {
	return input.Scene.Description == "" &&
		input.Scene.Purpose == "" &&
		input.Scene.PovCharacter == "" &&
		input.Scene.Location == "" &&
		input.Scene.PlotGoal == "" &&
		input.Scene.CharacterGoal == "" &&
		input.Scene.EmotionalGoal == "" &&
		!input.Scene.HasConflict &&
		input.Scene.ConflictType == ""
}

func (input *PlotStructureAnalysis) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Plot.CurrentAct)
	var1 := strconv.Itoa(input.Plot.TotalActs)
	var2 := strconv.Itoa(input.Plot.TensionLevel)
	length := 0
	length += 45
	length += len(input.Plot.StructureType)
	length += 18
	length += len(var0)
	length += 1
	length += len(var1)
	length += 29
	if input.Plot.IncitingIncident {
		length += 38
	}
	length += 2
	if input.Plot.FirstPlotPoint {
		length += 39
	}
	length += 2
	if input.Plot.Midpoint {
		length += 29
	}
	length += 2
	if input.Plot.Climax {
		length += 27
	}
	length += 2
	if input.Plot.Resolution {
		length += 31
	}
	length += 40
	length += len(input.Plot.Pacing)
	length += 20
	length += len(var2)
	length += 5
	if input.Plot.TensionLevel < 4 {
		length += 84
	}
	length += 2
	if input.Plot.TensionLevel > 8 {
		length += 93
	}
	length += 42
	length += len(input.Scene.Description)
	length += 14
	length += len(input.Scene.Purpose)
	length += 20
	length += len(input.Scene.PovCharacter)
	length += 14
	length += len(input.Scene.Location)
	length += 49
	length += len(input.Scene.PlotGoal)
	length += 31
	length += len(input.Scene.CharacterGoal)
	length += 24
	length += len(input.Scene.EmotionalGoal)
	length += 2
	if input.Scene.HasConflict {
		length += 79
		length += len(input.Scene.ConflictType)
		length += 1
	}
	b.Grow(length)
	b.WriteString("## 📊 Story Structure\n\n**Structure Type**: ")
	b.WriteString(input.Plot.StructureType)
	b.WriteString("\n**Current Act**: ")
	b.WriteString(var0)
	b.WriteString("/")
	b.WriteString(var1)
	b.WriteString("\n\n### Plot Points Checklist:\n")
	if input.Plot.IncitingIncident {
		b.WriteString("\n✅ **Inciting Incident**: Completed\n")
	}
	b.WriteString("\n\n")
	if input.Plot.FirstPlotPoint {
		b.WriteString("\n✅ **First Plot Point**: Completed  \n")
	}
	b.WriteString("\n\n")
	if input.Plot.Midpoint {
		b.WriteString("\n✅ **Midpoint**: Completed\n")
	}
	b.WriteString("\n\n")
	if input.Plot.Climax {
		b.WriteString("\n✅ **Climax**: Completed\n")
	}
	b.WriteString("\n\n")
	if input.Plot.Resolution {
		b.WriteString("\n✅ **Resolution**: Completed\n")
	}
	b.WriteString("\n\n### Pacing Analysis\n**Current Pace**: ")
	b.WriteString(input.Plot.Pacing)
	b.WriteString("\n**Tension Level**: ")
	b.WriteString(var2)
	b.WriteString("/10\n\n")
	if input.Plot.TensionLevel < 4 {
		b.WriteString("\n📈 **Pacing Note**: Consider adding more conflict or stakes to increase tension.\n")
	}
	b.WriteString("\n\n")
	if input.Plot.TensionLevel > 8 {
		b.WriteString("\n⚠️ **High Intensity**: Make sure to give readers breathing room between intense scenes.\n")
	}
	b.WriteString("\n\n## 🎯 Scene Goals\n\n**Today's Scene**: ")
	b.WriteString(input.Scene.Description)
	b.WriteString("\n**Purpose**: ")
	b.WriteString(input.Scene.Purpose)
	b.WriteString("\n**POV Character**: ")
	b.WriteString(input.Scene.PovCharacter)
	b.WriteString("\n**Setting**: ")
	b.WriteString(input.Scene.Location)
	b.WriteString("\n\n### Scene Objectives:\n1. **Plot Advancement**: ")
	b.WriteString(input.Scene.PlotGoal)
	b.WriteString("\n2. **Character Development**: ")
	b.WriteString(input.Scene.CharacterGoal)
	b.WriteString("\n3. **Emotional Beat**: ")
	b.WriteString(input.Scene.EmotionalGoal)
	b.WriteString("\n\n")
	if input.Scene.HasConflict {
		b.WriteString("\n✅ **Conflict Present**: Good! Every scene needs tension.\n**Conflict Type**: ")
		b.WriteString(input.Scene.ConflictType)
		b.WriteRune('\n')
	}
	return b.String()
}

type WritingProductivityDashboard struct {
	Session struct {
		DailyGoal          int
		WordsWritten       int
		ProgressPercentage int
		BonusWords         int
		StartTime          string
		EndTime            string
		NextGoal           string
	}
	Motivation struct {
		Tip string
	}
	Stats struct {
		WordsPerMinute    int
		SessionMinutes    int
		BreakMinutes      int
		WritingSpeedTrend string
	}
	Prompts struct {
		HasCustom           bool
		CustomPrompt        string
		CustomReason        string
		GeneralSuggestions  string
		CharacterExercise   string
		DialogueChallenge   string
		WorldbuildingPrompt string
	}
	Tools struct {
		GrammarCheck   bool
		ResearchNeeded bool
		ResearchTopics string
	}
	Writer struct {
		Experience string
		Name       string
	}
	Tips struct {
		BeginnerFocus     string
		AdvancedChallenge string
	}
}

func (input *WritingProductivityDashboard) isSessionZero() bool {
	return input.Session.DailyGoal == 0 &&
		input.Session.WordsWritten == 0 &&
		input.Session.ProgressPercentage == 0 &&
		input.Session.BonusWords == 0 &&
		input.Session.StartTime == "" &&
		input.Session.EndTime == "" &&
		input.Session.NextGoal == ""
}

func (input *WritingProductivityDashboard) isMotivationZero() bool {
	return input.Motivation.Tip == ""
}

func (input *WritingProductivityDashboard) isStatsZero() bool {
	return input.Stats.WordsPerMinute == 0 &&
		input.Stats.SessionMinutes == 0 &&
		input.Stats.BreakMinutes == 0 &&
		input.Stats.WritingSpeedTrend == ""
}

func (input *WritingProductivityDashboard) isPromptsZero() bool {
	return !input.Prompts.HasCustom &&
		input.Prompts.CustomPrompt == "" &&
		input.Prompts.CustomReason == "" &&
		input.Prompts.GeneralSuggestions == "" &&
		input.Prompts.CharacterExercise == "" &&
		input.Prompts.DialogueChallenge == "" &&
		input.Prompts.WorldbuildingPrompt == ""
}

func (input *WritingProductivityDashboard) isToolsZero() bool {
	return !input.Tools.GrammarCheck &&
		!input.Tools.ResearchNeeded &&
		input.Tools.ResearchTopics == ""
}

func (input *WritingProductivityDashboard) isWriterZero() bool {
	return input.Writer.Experience == "" &&
		input.Writer.Name == ""
}

func (input *WritingProductivityDashboard) isTipsZero() bool {
	return input.Tips.BeginnerFocus == "" &&
		input.Tips.AdvancedChallenge == ""
}

func (input *WritingProductivityDashboard) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Session.DailyGoal)
	var1 := strconv.Itoa(input.Session.WordsWritten)
	var2 := strconv.Itoa(input.Session.ProgressPercentage)
	var3 := strconv.Itoa(input.Session.BonusWords)
	var4 := strconv.Itoa(input.Stats.WordsPerMinute)
	var5 := strconv.Itoa(input.Stats.SessionMinutes)
	var6 := strconv.Itoa(input.Stats.BreakMinutes)
	length := 0
	length += 43
	length += len(var0)
	length += 29
	length += len(var1)
	length += 8
	length += len(var2)
	length += 4
	if input.Session.ProgressPercentage >= 100 {
		length += 48
		if input.Session.BonusWords != 0 {
			length += 19
			length += len(var3)
			length += 23
		}
		length += 1
	}
	length += 2
	if input.Session.ProgressPercentage < 50 {
		length += 75
		length += len(input.Motivation.Tip)
		length += 1
	}
	length += 47
	length += len(var4)
	length += 38
	length += len(var5)
	length += 27
	length += len(var6)
	length += 10
	if input.Stats.WritingSpeedTrend != "" {
		length += 18
		length += len(input.Stats.WritingSpeedTrend)
		length += 25
	}
	length += 41
	if input.Prompts.HasCustom {
		length += 34
		length += len(input.Prompts.CustomPrompt)
		length += 32
		length += len(input.Prompts.CustomReason)
		length += 1
	}
	length += 2
	if input.Prompts.GeneralSuggestions != "" {
		length += 58
		length += len(input.Prompts.CharacterExercise)
		length += 27
		length += len(input.Prompts.DialogueChallenge)
		length += 23
		length += len(input.Prompts.WorldbuildingPrompt)
		length += 1
	}
	length += 32
	if input.Tools.GrammarCheck {
		length += 90
	}
	length += 2
	if input.Tools.ResearchNeeded {
		length += 55
		length += len(input.Tools.ResearchTopics)
		length += 1
	}
	length += 2
	if input.Writer.Experience == "beginner" {
		length += 203
		length += len(input.Tips.BeginnerFocus)
		length += 1
	}
	length += 2
	if input.Writer.Experience == "advanced" {
		length += 170
		length += len(input.Tips.AdvancedChallenge)
		length += 1
	}
	length += 24
	length += len(input.Session.StartTime)
	length += 3
	length += len(input.Session.EndTime)
	length += 24
	length += len(input.Session.NextGoal)
	length += 17
	length += len(input.Writer.Name)
	length += 45
	b.Grow(length)
	b.WriteString("## 📈 Writing Metrics\n\n**Today's Goal**: ")
	b.WriteString(var0)
	b.WriteString(" words\n**Current Progress**: ")
	b.WriteString(var1)
	b.WriteString(" words (")
	b.WriteString(var2)
	b.WriteString("%)\n\n")
	if input.Session.ProgressPercentage >= 100 {
		b.WriteString("\n🎉 **Goal Achieved!** Fantastic work today!\n\n")
		if input.Session.BonusWords != 0 {
			b.WriteString("\n**Bonus Words**: +")
			b.WriteString(var3)
			b.WriteString(" words over your goal!\n")
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Session.ProgressPercentage < 50 {
		b.WriteString("\n💪 **Keep Going**: You're halfway to your goal! \n\n**Motivational Tip**: ")
		b.WriteString(input.Motivation.Tip)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n### Writing Statistics:\n- **Writing Speed**: ")
	b.WriteString(var4)
	b.WriteString(" words/minute\n- **Session Duration**: ")
	b.WriteString(var5)
	b.WriteString(" minutes\n- **Break Time**: ")
	b.WriteString(var6)
	b.WriteString(" minutes\n\n")
	if input.Stats.WritingSpeedTrend != "" {
		b.WriteString("\n**Speed Trend**: ")
		b.WriteString(input.Stats.WritingSpeedTrend)
		b.WriteString(" (compared to last week)\n")
	}
	b.WriteString("\n\n## 🎨 Writing Prompts & Inspiration\n\n")
	if input.Prompts.HasCustom {
		b.WriteString("\n### Personalized Prompt for You:\n")
		b.WriteString(input.Prompts.CustomPrompt)
		b.WriteString("\n\n**Why this fits your style**: ")
		b.WriteString(input.Prompts.CustomReason)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Prompts.GeneralSuggestions != "" {
		b.WriteString("\n### General Writing Exercises:\n- **Character Exercise**: ")
		b.WriteString(input.Prompts.CharacterExercise)
		b.WriteString("\n- **Dialogue Challenge**: ")
		b.WriteString(input.Prompts.DialogueChallenge)
		b.WriteString("\n- **World-Building**: ")
		b.WriteString(input.Prompts.WorldbuildingPrompt)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🔧 Writing Tools & Tips\n\n")
	if input.Tools.GrammarCheck {
		b.WriteString("\n📝 **Grammar Assistant**: Available - Run a quick check before finishing your session.\n")
	}
	b.WriteString("\n\n")
	if input.Tools.ResearchNeeded {
		b.WriteString("\n🔍 **Research Reminder**: Don't forget to research: ")
		b.WriteString(input.Tools.ResearchTopics)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Writer.Experience == "beginner" {
		b.WriteString("\n### Beginner Writer Tips:\n- Write first, edit later\n- Don't worry about perfection in your first draft\n- Read extensively in your chosen genre\n- Join a writing community for support\n\n**Today's Focus**: ")
		b.WriteString(input.Tips.BeginnerFocus)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Writer.Experience == "advanced" {
		b.WriteString("\n### Advanced Techniques:\n- Experiment with unreliable narrators\n- Layer multiple subplots effectively\n- Master show vs. tell\n- Develop your unique voice\n\n**Challenge**: ")
		b.WriteString(input.Tips.AdvancedChallenge)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n---\n**Session Time**: ")
	b.WriteString(input.Session.StartTime)
	b.WriteString(" - ")
	b.WriteString(input.Session.EndTime)
	b.WriteString("\n**Next Session Goal**: ")
	b.WriteString(input.Session.NextGoal)
	b.WriteString("\n\n*Keep writing, ")
	b.WriteString(input.Writer.Name)
	b.WriteString("! Your story is waiting to be told. 📚✨* ")
	return b.String()
}
