// Code generated by agentflow v0.4.2; DO NOT EDIT.

package minimaltest

import (
	"strconv"
	"strings"
)

type TestBasic struct {
	Name string
}

func (input *TestBasic) String() string {
	var b strings.Builder
	length := 0
	length += 29
	length += len(input.Name)
	length += 1
	b.Grow(length)
	b.WriteString("Simple test with backticks: `")
	b.WriteString(input.Name)
	b.WriteString("`")
	return b.String()
}

type TestConditional struct {
	User struct {
		Premium bool
	}
}

func (input *TestConditional) isUserZero() bool {
	return !input.User.Premium
}

func (input *TestConditional) String() string {
	var b strings.Builder
	length := 0
	if input.User.Premium {
		length += 31
	} else {
		length += 31
	}
	b.Grow(length)
	if input.User.Premium {
		b.WriteString("\nPremium user with `backticks`\n")
	} else {
		b.WriteString("\nRegular user with `backticks`\n")
	}
	return b.String()
}

type TestNested struct {
	Outer string
	Inner string
}

func (input *TestNested) String() string {
	var b strings.Builder
	length := 0
	if input.Outer != "" {
		length += 13
		if input.Inner != "" {
			length += 15
		}
		length += 11
	}
	b.Grow(length)
	if input.Outer != "" {
		b.WriteString(`
Outer start
`)
		if input.Inner != "" {
			b.WriteString(`
Inner content
`)
		}
		b.WriteString(`
Outer end
`)
	}
	return b.String()
}

type TestComparison struct {
	Age int
}

func (input *TestComparison) String() string {
	var b strings.Builder
	length := 0
	if input.Age >= 18 {
		length += 24
		length += len(strconv.Itoa(input.Age))
		length += 2
	} else {
		length += 23
		length += len(strconv.Itoa(input.Age))
		length += 2
	}
	length += 1
	b.Grow(length)
	if input.Age >= 18 {
		b.WriteString(`
You are an adult (age: `)
		b.WriteString(strconv.Itoa(input.Age))
		b.WriteString(`)
`)
	} else {
		b.WriteString(`
You are a minor (age: `)
		b.WriteString(strconv.Itoa(input.Age))
		b.WriteString(`)
`)
	}
	b.WriteString(` `)
	return b.String()
}
