// Code generated by agentflow v0.5.0; DO NOT EDIT.

package apidocs

import (
	"strconv"
	"strings"
)

type ApiDocumentationGenerator struct{}

func (input *ApiDocumentationGenerator) String() string {
	return "You are APIDocBot, an intelligent documentation generator that creates comprehensive, up-to-date API documentation with interactive examples, versioning support, and developer-friendly formatting."
}

type ApiOverview struct {
	Api struct {
		Name               string
		Version            string
		BaseUrl            string
		Protocol           string
		AuthType           string
		Deprecated         bool
		ReplacementVersion string
		SunsetDate         string
		Beta               bool
		StabilityLevel     string
	}
	Changelog struct {
		HasBreakingChanges bool
		BreakingChanges    string
		NewFeatures        string
		Improvements       string
		BugFixes           string
	}
	Docs struct {
		MigrationUrl string
	}
	Auth struct {
		Type         string
		Required     bool
		DashboardUrl string
		OauthFlow    string
		Scopes       string
		AuthUrl      string
		TokenUrl     string
		ScopeCount   int
		ScopeList    string
		HeaderName   string
		QueryParam   string
		RateLimits   bool
	}
	RateLimits struct {
		StandardRequests int
		StandardWindow   string
		PremiumRequests  int
		PremiumWindow    string
		HasBurst         bool
		BurstRequests    int
		BurstWindow      string
	}
}

func (input *ApiOverview) isApiZero() bool {
	return input.Api.Name == "" &&
		input.Api.Version == "" &&
		input.Api.BaseUrl == "" &&
		input.Api.Protocol == "" &&
		input.Api.AuthType == "" &&
		!input.Api.Deprecated &&
		input.Api.ReplacementVersion == "" &&
		input.Api.SunsetDate == "" &&
		!input.Api.Beta &&
		input.Api.StabilityLevel == ""
}

func (input *ApiOverview) isChangelogZero() bool {
	return !input.Changelog.HasBreakingChanges &&
		input.Changelog.BreakingChanges == "" &&
		input.Changelog.NewFeatures == "" &&
		input.Changelog.Improvements == "" &&
		input.Changelog.BugFixes == ""
}

func (input *ApiOverview) isDocsZero() bool {
	return input.Docs.MigrationUrl == ""
}

func (input *ApiOverview) isAuthZero() bool {
	return input.Auth.Type == "" &&
		!input.Auth.Required &&
		input.Auth.DashboardUrl == "" &&
		input.Auth.OauthFlow == "" &&
		input.Auth.Scopes == "" &&
		input.Auth.AuthUrl == "" &&
		input.Auth.TokenUrl == "" &&
		input.Auth.ScopeCount == 0 &&
		input.Auth.ScopeList == "" &&
		input.Auth.HeaderName == "" &&
		input.Auth.QueryParam == "" &&
		!input.Auth.RateLimits
}

func (input *ApiOverview) isRateLimitsZero() bool {
	return input.RateLimits.StandardRequests == 0 &&
		input.RateLimits.StandardWindow == "" &&
		input.RateLimits.PremiumRequests == 0 &&
		input.RateLimits.PremiumWindow == "" &&
		!input.RateLimits.HasBurst &&
		input.RateLimits.BurstRequests == 0 &&
		input.RateLimits.BurstWindow == ""
}

func (input *ApiOverview) String() string {
	var b strings.Builder
	var0 := strconv.FormatBool(input.Auth.Required)
	var1 := strconv.Itoa(input.RateLimits.StandardRequests)
	var2 := strconv.Itoa(input.RateLimits.PremiumRequests)
	var3 := strconv.Itoa(input.RateLimits.BurstRequests)
	length := 0
	length += 7
	length += len(input.Api.Name)
	length += 33
	length += len(input.Api.Version)
	length += 16
	length += len(input.Api.BaseUrl)
	length += 16
	length += len(input.Api.Protocol)
	length += 21
	length += len(input.Api.AuthType)
	length += 2
	if input.Api.Deprecated {
		length += 86
		length += len(input.Api.ReplacementVersion)
		length += 19
		length += len(input.Api.SunsetDate)
		length += 1
	}
	length += 2
	if input.Api.Beta {
		length += 92
		length += len(input.Api.StabilityLevel)
		length += 3
	}
	length += 25
	length += len(input.Api.Version)
	length += 2
	if input.Changelog.HasBreakingChanges {
		length += 27
		length += len(input.Changelog.BreakingChanges)
		length += 59
		length += len(input.Docs.MigrationUrl)
		length += 28
	}
	length += 2
	if input.Changelog.NewFeatures != "" {
		length += 22
		length += len(input.Changelog.NewFeatures)
		length += 1
	}
	length += 2
	if input.Changelog.Improvements != "" {
		length += 23
		length += len(input.Changelog.Improvements)
		length += 1
	}
	length += 2
	if input.Changelog.BugFixes != "" {
		length += 20
		length += len(input.Changelog.BugFixes)
		length += 1
	}
	length += 36
	length += len(input.Auth.Type)
	length += 15
	length += len(var0)
	length += 2
	if input.Auth.Type == "bearer" {
		length += 176
		length += len(input.Auth.DashboardUrl)
		length += 2
	}
	length += 2
	if input.Auth.Type == "oauth2" {
		length += 40
		length += len(input.Auth.OauthFlow)
		length += 13
		length += len(input.Auth.Scopes)
		length += 26
		length += len(input.Auth.AuthUrl)
		length += 18
		length += len(input.Auth.TokenUrl)
		length += 25
		if input.Auth.ScopeCount != 0 {
			length += 1
			length += len(input.Auth.ScopeList)
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Auth.Type == "apikey" {
		length += 41
		length += len(input.Auth.HeaderName)
		length += 24
		length += len(input.Auth.QueryParam)
		length += 25
		length += len(input.Auth.HeaderName)
		length += 19
	}
	length += 2
	if input.Auth.RateLimits {
		length += 41
		length += len(var1)
		length += 10
		length += len(input.RateLimits.StandardWindow)
		length += 19
		length += len(var2)
		length += 10
		length += len(input.RateLimits.PremiumWindow)
		length += 165
		if input.RateLimits.HasBurst {
			length += 22
			length += len(var3)
			length += 13
			length += len(input.RateLimits.BurstWindow)
			length += 9
		}
		length += 1
	}
	b.Grow(length)
	b.WriteString("# 📡 ")
	b.WriteString(input.Api.Name)
	b.WriteString(" API Documentation\n\n**Version**: ")
	b.WriteString(input.Api.Version)
	b.WriteString("\n**Base URL**: `")
	b.WriteString(input.Api.BaseUrl)
	b.WriteString("`\n**Protocol**: ")
	b.WriteString(input.Api.Protocol)
	b.WriteString("\n**Authentication**: ")
	b.WriteString(input.Api.AuthType)
	b.WriteString("\n\n")
	if input.Api.Deprecated {
		b.WriteString("\n⚠️ **DEPRECATED API**: This API version is deprecated. Please migrate to version ")
		b.WriteString(input.Api.ReplacementVersion)
		b.WriteString(".\n**Sunset Date**: ")
		b.WriteString(input.Api.SunsetDate)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Api.Beta {
		b.WriteString("\n🧪 **BETA API**: This API is in beta. Features may change without notice.\n**Stability**: ")
		b.WriteString(input.Api.StabilityLevel)
		b.WriteString("/5\n")
	}
	b.WriteString("\n\n## 🌟 What's New in v")
	b.WriteString(input.Api.Version)
	b.WriteString("\n\n")
	if input.Changelog.HasBreakingChanges {
		b.WriteString("\n### 💥 Breaking Changes\n")
		b.WriteString(input.Changelog.BreakingChanges)
		b.WriteString("\n\n⚠️ **Migration Required**: See our [migration guide](")
		b.WriteString(input.Docs.MigrationUrl)
		b.WriteString(") for upgrade instructions.\n")
	}
	b.WriteString("\n\n")
	if input.Changelog.NewFeatures != "" {
		b.WriteString("\n### ✨ New Features\n")
		b.WriteString(input.Changelog.NewFeatures)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Changelog.Improvements != "" {
		b.WriteString("\n### 🚀 Improvements\n")
		b.WriteString(input.Changelog.Improvements)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Changelog.BugFixes != "" {
		b.WriteString("\n### 🐛 Bug Fixes\n")
		b.WriteString(input.Changelog.BugFixes)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🔐 Authentication\n\n**Type**: ")
	b.WriteString(input.Auth.Type)
	b.WriteString("\n**Required**: ")
	b.WriteString(var0)
	b.WriteString("\n\n")
	if input.Auth.Type == "bearer" {
		b.WriteString("\n### Bearer Token Authentication\nInclude your API key in the Authorization header:\n\n```http\nAuthorization: Bearer YOUR_API_KEY\n```\n\n**Get your API key**: [Developer Dashboard](")
		b.WriteString(input.Auth.DashboardUrl)
		b.WriteString(")\n")
	}
	b.WriteString("\n\n")
	if input.Auth.Type == "oauth2" {
		b.WriteString("\n### OAuth 2.0 Authentication\n**Flow**: ")
		b.WriteString(input.Auth.OauthFlow)
		b.WriteString("\n**Scopes**: ")
		b.WriteString(input.Auth.Scopes)
		b.WriteString("\n\n**Authorization URL**: `")
		b.WriteString(input.Auth.AuthUrl)
		b.WriteString("`\n**Token URL**: `")
		b.WriteString(input.Auth.TokenUrl)
		b.WriteString("`\n\n#### Required Scopes:\n")
		if input.Auth.ScopeCount != 0 {
			b.WriteRune('\n')
			b.WriteString(input.Auth.ScopeList)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Auth.Type == "apikey" {
		b.WriteString("\n### API Key Authentication\n**Header**: `")
		b.WriteString(input.Auth.HeaderName)
		b.WriteString("`\n**Query Parameter**: `")
		b.WriteString(input.Auth.QueryParam)
		b.WriteString("` (alternative)\n\n```http\n")
		b.WriteString(input.Auth.HeaderName)
		b.WriteString(": YOUR_API_KEY\n```\n")
	}
	b.WriteString("\n\n")
	if input.Auth.RateLimits {
		b.WriteString("\n## 📊 Rate Limits\n\n**Standard Tier**: ")
		b.WriteString(var1)
		b.WriteString(" requests/")
		b.WriteString(input.RateLimits.StandardWindow)
		b.WriteString("\n**Premium Tier**: ")
		b.WriteString(var2)
		b.WriteString(" requests/")
		b.WriteString(input.RateLimits.PremiumWindow)
		b.WriteString("\n\n**Rate Limit Headers**:\n- `X-RateLimit-Limit`: Total requests allowed\n- `X-RateLimit-Remaining`: Requests remaining\n- `X-RateLimit-Reset`: Time when limit resets\n\n")
		if input.RateLimits.HasBurst {
			b.WriteString("\n**Burst Allowance**: ")
			b.WriteString(var3)
			b.WriteString(" requests in ")
			b.WriteString(input.RateLimits.BurstWindow)
			b.WriteString(" seconds\n")
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type EndpointDocumentation struct {
	Endpoints struct {
		Count          int
		HasCategories  bool
		UserManagement bool
		UserCount      int
		DataOperations bool
		DataCount      int
		Analytics      bool
		AnalyticsCount int
		Webhooks       bool
		WebhookCount   int
	}
	Endpoint struct {
		Featured         bool
		Name             string
		Method           string
		Path             string
		Description      string
		RequiresAuth     bool
		HasPathParams    bool
		PathParams       string
		ParamName        string
		ParamType        string
		ParamRequired    bool
		ParamDescription string
		HasQueryParams   bool
		QueryParams      string
		QueryName        string
		QueryType        string
		QueryRequired    bool
		QueryDefault     string
		QueryDescription string
		HasBody          bool
		RequestBody      string
		RequestSchema    string
		SuccessCodes     string
		ResponseExample  string
		HasErrorCodes    bool
		ErrorCodes       string
		ErrorCode        int
		ErrorDescription string
		ErrorSolution    string
		CurlBody         string
		JsBody           string
		PythonBody       string
		MethodLower      string
		NoBody           bool
		GoBody           string
	}
	Api struct {
		BaseUrl string
	}
	Examples struct {
		Curl       bool
		Javascript bool
		Python     bool
		Go         bool
	}
}

func (input *EndpointDocumentation) isEndpointsZero() bool {
	return input.Endpoints.Count == 0 &&
		!input.Endpoints.HasCategories &&
		!input.Endpoints.UserManagement &&
		input.Endpoints.UserCount == 0 &&
		!input.Endpoints.DataOperations &&
		input.Endpoints.DataCount == 0 &&
		!input.Endpoints.Analytics &&
		input.Endpoints.AnalyticsCount == 0 &&
		!input.Endpoints.Webhooks &&
		input.Endpoints.WebhookCount == 0
}

func (input *EndpointDocumentation) isEndpointZero() bool {
	return !input.Endpoint.Featured &&
		input.Endpoint.Name == "" &&
		input.Endpoint.Method == "" &&
		input.Endpoint.Path == "" &&
		input.Endpoint.Description == "" &&
		!input.Endpoint.RequiresAuth &&
		!input.Endpoint.HasPathParams &&
		input.Endpoint.PathParams == "" &&
		input.Endpoint.ParamName == "" &&
		input.Endpoint.ParamType == "" &&
		!input.Endpoint.ParamRequired &&
		input.Endpoint.ParamDescription == "" &&
		!input.Endpoint.HasQueryParams &&
		input.Endpoint.QueryParams == "" &&
		input.Endpoint.QueryName == "" &&
		input.Endpoint.QueryType == "" &&
		!input.Endpoint.QueryRequired &&
		input.Endpoint.QueryDefault == "" &&
		input.Endpoint.QueryDescription == "" &&
		!input.Endpoint.HasBody &&
		input.Endpoint.RequestBody == "" &&
		input.Endpoint.RequestSchema == "" &&
		input.Endpoint.SuccessCodes == "" &&
		input.Endpoint.ResponseExample == "" &&
		!input.Endpoint.HasErrorCodes &&
		input.Endpoint.ErrorCodes == "" &&
		input.Endpoint.ErrorCode == 0 &&
		input.Endpoint.ErrorDescription == "" &&
		input.Endpoint.ErrorSolution == "" &&
		input.Endpoint.CurlBody == "" &&
		input.Endpoint.JsBody == "" &&
		input.Endpoint.PythonBody == "" &&
		input.Endpoint.MethodLower == "" &&
		!input.Endpoint.NoBody &&
		input.Endpoint.GoBody == ""
}

func (input *EndpointDocumentation) isApiZero() bool {
	return input.Api.BaseUrl == ""
}

func (input *EndpointDocumentation) isExamplesZero() bool {
	return !input.Examples.Curl &&
		!input.Examples.Javascript &&
		!input.Examples.Python &&
		!input.Examples.Go
}

func (input *EndpointDocumentation) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Endpoints.Count)
	var1 := strconv.Itoa(input.Endpoints.UserCount)
	var2 := strconv.Itoa(input.Endpoints.DataCount)
	var3 := strconv.Itoa(input.Endpoints.AnalyticsCount)
	var4 := strconv.Itoa(input.Endpoints.WebhookCount)
	var5 := strconv.FormatBool(input.Endpoint.ParamRequired)
	var6 := strconv.FormatBool(input.Endpoint.QueryRequired)
	var7 := strconv.Itoa(input.Endpoint.ErrorCode)
	length := 0
	if input.Endpoints.Count != 0 {
		length += 30
		length += len(var0)
		length += 9
		if input.Endpoints.HasCategories {
			length += 26
			if input.Endpoints.UserManagement {
				length += 29
				length += len(var1)
				length += 11
			}
			length += 1
			if input.Endpoints.DataOperations {
				length += 29
				length += len(var2)
				length += 13
			}
			length += 1
			if input.Endpoints.Analytics {
				length += 23
				length += len(var3)
				length += 11
			}
			length += 1
			if input.Endpoints.Webhooks {
				length += 22
				length += len(var4)
				length += 11
			}
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Endpoint.Featured {
		length += 28
		length += len(input.Endpoint.Name)
		length += 15
		length += len(input.Endpoint.Method)
		length += 13
		length += len(input.Endpoint.Path)
		length += 15
		length += len(input.Endpoint.Description)
		length += 23
		length += len(input.Endpoint.Method)
		length += 1
		length += len(input.Api.BaseUrl)
		length += len(input.Endpoint.Path)
		length += 32
		if input.Endpoint.RequiresAuth {
			length += 36
		}
		length += 6
		if input.Endpoint.HasPathParams {
			length += 114
			if input.Endpoint.PathParams != "" {
				length += 3
				length += len(input.Endpoint.ParamName)
				length += 3
				length += len(input.Endpoint.ParamType)
				length += 3
				length += len(var5)
				length += 3
				length += len(input.Endpoint.ParamDescription)
				length += 3
			}
			length += 1
		}
		length += 2
		if input.Endpoint.HasQueryParams {
			length += 135
			if input.Endpoint.QueryParams != "" {
				length += 3
				length += len(input.Endpoint.QueryName)
				length += 3
				length += len(input.Endpoint.QueryType)
				length += 3
				length += len(var6)
				length += 3
				length += len(input.Endpoint.QueryDefault)
				length += 3
				length += len(input.Endpoint.QueryDescription)
				length += 3
			}
			length += 1
		}
		length += 2
		if input.Endpoint.HasBody {
			length += 28
			length += len(input.Endpoint.RequestBody)
			length += 18
			length += len(input.Endpoint.RequestSchema)
			length += 1
		}
		length += 16
		if input.Endpoint.SuccessCodes != "" {
			length += 20
			length += len(input.Endpoint.SuccessCodes)
			length += 1
		}
		length += 10
		length += len(input.Endpoint.ResponseExample)
		length += 6
		if input.Endpoint.HasErrorCodes {
			length += 91
			if input.Endpoint.ErrorCodes != "" {
				length += 3
				length += len(var7)
				length += 3
				length += len(input.Endpoint.ErrorDescription)
				length += 3
				length += len(input.Endpoint.ErrorSolution)
				length += 3
			}
			length += 1
		}
		length += 21
		if input.Examples.Curl {
			length += 27
			length += len(input.Endpoint.Method)
			length += 6
			length += len(input.Api.BaseUrl)
			length += len(input.Endpoint.Path)
			length += 44
			if input.Endpoint.RequiresAuth {
				length += 45
			}
			length += 1
			if input.Endpoint.HasBody {
				length += 7
				length += len(input.Endpoint.CurlBody)
				length += 2
			}
			length += 5
		}
		length += 2
		if input.Examples.Javascript {
			length += 69
			length += len(input.Api.BaseUrl)
			length += len(input.Endpoint.Path)
			length += 16
			length += len(input.Endpoint.Method)
			length += 56
			if input.Endpoint.RequiresAuth {
				length += 45
			}
			length += 6
			if input.Endpoint.HasBody {
				length += 24
				length += len(input.Endpoint.JsBody)
				length += 2
			}
			length += 65
		}
		length += 2
		if input.Examples.Python {
			length += 58
			length += len(input.Api.BaseUrl)
			length += len(input.Endpoint.Path)
			length += 2
			if input.Endpoint.RequiresAuth {
				length += 98
			}
			length += 1
			if input.Endpoint.HasBody {
				length += 8
				length += len(input.Endpoint.PythonBody)
				length += 22
				length += len(input.Endpoint.MethodLower)
				length += 34
			}
			length += 1
			if input.Endpoint.NoBody {
				length += 21
				length += len(input.Endpoint.MethodLower)
				length += 23
			}
			length += 28
		}
		length += 2
		if input.Examples.Go {
			length += 124
			length += len(input.Api.BaseUrl)
			length += len(input.Endpoint.Path)
			length += 7
			if input.Endpoint.HasBody {
				length += 13
				length += len(input.Endpoint.GoBody)
				length += 75
				length += len(input.Endpoint.Method)
				length += 35
			}
			length += 1
			if input.Endpoint.NoBody {
				length += 32
				length += len(input.Endpoint.Method)
				length += 13
			}
			length += 61
			if input.Endpoint.RequiresAuth {
				length += 60
			}
			length += 130
		}
		length += 1
	}
	b.Grow(length)
	if input.Endpoints.Count != 0 {
		b.WriteString("\n## 📚 Available Endpoints (")
		b.WriteString(var0)
		b.WriteString(" total)\n\n")
		if input.Endpoints.HasCategories {
			b.WriteString("\n### Endpoint Categories:\n")
			if input.Endpoints.UserManagement {
				b.WriteString("\n- **👤 User Management**: ")
				b.WriteString(var1)
				b.WriteString(" endpoints\n")
			}
			b.WriteRune('\n')
			if input.Endpoints.DataOperations {
				b.WriteString("\n- **💾 Data Operations**: ")
				b.WriteString(var2)
				b.WriteString(" endpoints  \n")
			}
			b.WriteRune('\n')
			if input.Endpoints.Analytics {
				b.WriteString("\n- **📊 Analytics**: ")
				b.WriteString(var3)
				b.WriteString(" endpoints\n")
			}
			b.WriteRune('\n')
			if input.Endpoints.Webhooks {
				b.WriteString("\n- **🔗 Webhooks**: ")
				b.WriteString(var4)
				b.WriteString(" endpoints\n")
			}
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Endpoint.Featured {
		b.WriteString("\n## 🌟 Featured Endpoint: ")
		b.WriteString(input.Endpoint.Name)
		b.WriteString("\n\n**Method**: `")
		b.WriteString(input.Endpoint.Method)
		b.WriteString("`\n**Path**: `")
		b.WriteString(input.Endpoint.Path)
		b.WriteString("`\n**Purpose**: ")
		b.WriteString(input.Endpoint.Description)
		b.WriteString("\n\n### Request\n\n```http\n")
		b.WriteString(input.Endpoint.Method)
		b.WriteString(" ")
		b.WriteString(input.Api.BaseUrl)
		b.WriteString(input.Endpoint.Path)
		b.WriteString("\nContent-Type: application/json\n")
		if input.Endpoint.RequiresAuth {
			b.WriteString("\nAuthorization: Bearer YOUR_API_KEY\n")
		}
		b.WriteString("\n```\n\n")
		if input.Endpoint.HasPathParams {
			b.WriteString("\n#### Path Parameters\n| Parameter | Type | Required | Description |\n|-----------|------|----------|-------------|\n")
			if input.Endpoint.PathParams != "" {
				b.WriteString("\n| ")
				b.WriteString(input.Endpoint.ParamName)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.ParamType)
				b.WriteString(" | ")
				b.WriteString(var5)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.ParamDescription)
				b.WriteString(" |\n")
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Endpoint.HasQueryParams {
			b.WriteString("\n#### Query Parameters\n| Parameter | Type | Required | Default | Description |\n|-----------|------|----------|---------|-------------|\n")
			if input.Endpoint.QueryParams != "" {
				b.WriteString("\n| ")
				b.WriteString(input.Endpoint.QueryName)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.QueryType)
				b.WriteString(" | ")
				b.WriteString(var6)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.QueryDefault)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.QueryDescription)
				b.WriteString(" |\n")
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Endpoint.HasBody {
			b.WriteString("\n#### Request Body\n\n```json\n")
			b.WriteString(input.Endpoint.RequestBody)
			b.WriteString("\n```\n\n**Schema**: ")
			b.WriteString(input.Endpoint.RequestSchema)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n### Response\n\n")
		if input.Endpoint.SuccessCodes != "" {
			b.WriteString("\n**Success Codes**: ")
			b.WriteString(input.Endpoint.SuccessCodes)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n```json\n")
		b.WriteString(input.Endpoint.ResponseExample)
		b.WriteString("\n```\n\n")
		if input.Endpoint.HasErrorCodes {
			b.WriteString("\n#### Error Responses\n\n| Code | Description | Solution |\n|------|-------------|----------|\n")
			if input.Endpoint.ErrorCodes != "" {
				b.WriteString("\n| ")
				b.WriteString(var7)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.ErrorDescription)
				b.WriteString(" | ")
				b.WriteString(input.Endpoint.ErrorSolution)
				b.WriteString(" |\n")
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n### Code Examples\n\n")
		if input.Examples.Curl {
			b.WriteString("\n#### cURL\n```bash\ncurl -X ")
			b.WriteString(input.Endpoint.Method)
			b.WriteString(" \\\n  '")
			b.WriteString(input.Api.BaseUrl)
			b.WriteString(input.Endpoint.Path)
			b.WriteString("' \\\n  -H 'Content-Type: application/json' \\\n")
			if input.Endpoint.RequiresAuth {
				b.WriteString("\n  -H 'Authorization: Bearer YOUR_API_KEY' \\\n")
			}
			b.WriteRune('\n')
			if input.Endpoint.HasBody {
				b.WriteString("\n  -d '")
				b.WriteString(input.Endpoint.CurlBody)
				b.WriteString("'\n")
			}
			b.WriteString("\n```\n")
		}
		b.WriteString("\n\n")
		if input.Examples.Javascript {
			b.WriteString("\n#### JavaScript (fetch)\n```javascript\nconst response = await fetch('")
			b.WriteString(input.Api.BaseUrl)
			b.WriteString(input.Endpoint.Path)
			b.WriteString("', {\n  method: '")
			b.WriteString(input.Endpoint.Method)
			b.WriteString("',\n  headers: {\n    'Content-Type': 'application/json',\n")
			if input.Endpoint.RequiresAuth {
				b.WriteString("\n    'Authorization': 'Bearer YOUR_API_KEY',\n")
			}
			b.WriteString("\n  },\n")
			if input.Endpoint.HasBody {
				b.WriteString("\n  body: JSON.stringify(")
				b.WriteString(input.Endpoint.JsBody)
				b.WriteString(")\n")
			}
			b.WriteString("\n});\n\nconst data = await response.json();\nconsole.log(data);\n```\n")
		}
		b.WriteString("\n\n")
		if input.Examples.Python {
			b.WriteString("\n#### Python (requests)\n```python\nimport requests\n\nurl = \"")
			b.WriteString(input.Api.BaseUrl)
			b.WriteString(input.Endpoint.Path)
			b.WriteString("\"\n")
			if input.Endpoint.RequiresAuth {
				b.WriteString("\nheaders = {\n    \"Content-Type\": \"application/json\",\n    \"Authorization\": \"Bearer YOUR_API_KEY\"\n}\n")
			}
			b.WriteRune('\n')
			if input.Endpoint.HasBody {
				b.WriteString("\ndata = ")
				b.WriteString(input.Endpoint.PythonBody)
				b.WriteString("\n\nresponse = requests.")
				b.WriteString(input.Endpoint.MethodLower)
				b.WriteString("(url, headers=headers, json=data)\n")
			}
			b.WriteRune('\n')
			if input.Endpoint.NoBody {
				b.WriteString("\nresponse = requests.")
				b.WriteString(input.Endpoint.MethodLower)
				b.WriteString("(url, headers=headers)\n")
			}
			b.WriteString("\nprint(response.json())\n```\n")
		}
		b.WriteString("\n\n")
		if input.Examples.Go {
			b.WriteString("\n#### Go\n```go\npackage main\n\nimport (\n    \"bytes\"\n    \"encoding/json\"\n    \"fmt\"\n    \"net/http\"\n)\n\nfunc main() {\n    url := \"")
			b.WriteString(input.Api.BaseUrl)
			b.WriteString(input.Endpoint.Path)
			b.WriteString("\"\n    \n")
			if input.Endpoint.HasBody {
				b.WriteString("\n    data := ")
				b.WriteString(input.Endpoint.GoBody)
				b.WriteString("\n    jsonData, _ := json.Marshal(data)\n    \n    req, _ := http.NewRequest(\"")
				b.WriteString(input.Endpoint.Method)
				b.WriteString("\", url, bytes.NewBuffer(jsonData))\n")
			}
			b.WriteRune('\n')
			if input.Endpoint.NoBody {
				b.WriteString("\n    req, _ := http.NewRequest(\"")
				b.WriteString(input.Endpoint.Method)
				b.WriteString("\", url, nil)\n")
			}
			b.WriteString("\n    \n    req.Header.Set(\"Content-Type\", \"application/json\")\n")
			if input.Endpoint.RequiresAuth {
				b.WriteString("\n    req.Header.Set(\"Authorization\", \"Bearer YOUR_API_KEY\")\n")
			}
			b.WriteString("\n    \n    client := &http.Client{}\n    resp, _ := client.Do(req)\n    defer resp.Body.Close()\n    \n    // Handle response...\n}\n```\n")
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type SchemaReference struct {
	Schemas struct {
		Available bool
		Count     int
		Schema1   struct {
			Name            string
			Description     string
			Example         string
			Properties      string
			HasValidation   bool
			ValidationRules string
		}
		FieldName        string
		FieldType        string
		FieldRequired    bool
		FieldDescription string
	}
}

func (input *SchemaReference) isSchemasZero() bool {
	return !input.Schemas.Available &&
		input.Schemas.Count == 0 &&
		input.isSchemasSchema1Zero() &&
		input.Schemas.FieldName == "" &&
		input.Schemas.FieldType == "" &&
		!input.Schemas.FieldRequired &&
		input.Schemas.FieldDescription == ""
}

func (input *SchemaReference) isSchemasSchema1Zero() bool {
	return input.Schemas.Schema1.Name == "" &&
		input.Schemas.Schema1.Description == "" &&
		input.Schemas.Schema1.Example == "" &&
		input.Schemas.Schema1.Properties == "" &&
		!input.Schemas.Schema1.HasValidation &&
		input.Schemas.Schema1.ValidationRules == ""
}

func (input *SchemaReference) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Schemas.Count)
	var1 := strconv.FormatBool(input.Schemas.FieldRequired)
	length := 0
	if input.Schemas.Available {
		length += 23
		if input.Schemas.Count != 0 {
			length += 24
			length += len(var0)
			length += 9
			if !input.isSchemasSchema1Zero() {
				length += 6
				length += len(input.Schemas.Schema1.Name)
				length += 19
				length += len(input.Schemas.Schema1.Description)
				length += 10
				length += len(input.Schemas.Schema1.Example)
				length += 106
				if input.Schemas.Schema1.Properties != "" {
					length += 3
					length += len(input.Schemas.FieldName)
					length += 3
					length += len(input.Schemas.FieldType)
					length += 3
					length += len(var1)
					length += 3
					length += len(input.Schemas.FieldDescription)
					length += 3
				}
				length += 2
				if input.Schemas.Schema1.HasValidation {
					length += 23
					length += len(input.Schemas.Schema1.ValidationRules)
					length += 1
				}
				length += 1
			}
			length += 1
		}
		length += 1
	}
	b.Grow(length)
	if input.Schemas.Available {
		b.WriteString("\n## 📋 Data Schemas\n\n")
		if input.Schemas.Count != 0 {
			b.WriteString("\n### Available Schemas (")
			b.WriteString(var0)
			b.WriteString(" total)\n\n")
			if !input.isSchemasSchema1Zero() {
				b.WriteString("\n#### ")
				b.WriteString(input.Schemas.Schema1.Name)
				b.WriteString("\n\n**Description**: ")
				b.WriteString(input.Schemas.Schema1.Description)
				b.WriteString("\n\n```json\n")
				b.WriteString(input.Schemas.Schema1.Example)
				b.WriteString("\n```\n\n**Properties**:\n| Field | Type | Required | Description |\n|-------|------|----------|-------------|\n")
				if input.Schemas.Schema1.Properties != "" {
					b.WriteString("\n| ")
					b.WriteString(input.Schemas.FieldName)
					b.WriteString(" | ")
					b.WriteString(input.Schemas.FieldType)
					b.WriteString(" | ")
					b.WriteString(var1)
					b.WriteString(" | ")
					b.WriteString(input.Schemas.FieldDescription)
					b.WriteString(" |\n")
				}
				b.WriteString("\n\n")
				if input.Schemas.Schema1.HasValidation {
					b.WriteString("\n**Validation Rules**:\n")
					b.WriteString(input.Schemas.Schema1.ValidationRules)
					b.WriteRune('\n')
				}
				b.WriteRune('\n')
			}
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type SdksAndTools struct {
	Sdks struct {
		Available      bool
		OfficialCount  int
		Javascript     bool
		JsPackage      string
		JsDocs         string
		JsVersion      string
		JsSize         string
		Python         bool
		PythonPackage  string
		PythonDocs     string
		PythonVersion  string
		PythonCompat   string
		Go             bool
		GoPackage      string
		GoDocs         string
		GoVersion      string
		GoCompat       string
		Ruby           bool
		RubyPackage    string
		RubyDocs       string
		RubyVersion    string
		CommunityCount int
		CommunityList  string
	}
	Tools struct {
		Postman     bool
		PostmanUrl  string
		Openapi     bool
		OpenapiUrl  string
		SwaggerUrl  string
		Insomnia    bool
		InsomniaUrl string
	}
}

func (input *SdksAndTools) isSdksZero() bool {
	return !input.Sdks.Available &&
		input.Sdks.OfficialCount == 0 &&
		!input.Sdks.Javascript &&
		input.Sdks.JsPackage == "" &&
		input.Sdks.JsDocs == "" &&
		input.Sdks.JsVersion == "" &&
		input.Sdks.JsSize == "" &&
		!input.Sdks.Python &&
		input.Sdks.PythonPackage == "" &&
		input.Sdks.PythonDocs == "" &&
		input.Sdks.PythonVersion == "" &&
		input.Sdks.PythonCompat == "" &&
		!input.Sdks.Go &&
		input.Sdks.GoPackage == "" &&
		input.Sdks.GoDocs == "" &&
		input.Sdks.GoVersion == "" &&
		input.Sdks.GoCompat == "" &&
		!input.Sdks.Ruby &&
		input.Sdks.RubyPackage == "" &&
		input.Sdks.RubyDocs == "" &&
		input.Sdks.RubyVersion == "" &&
		input.Sdks.CommunityCount == 0 &&
		input.Sdks.CommunityList == ""
}

func (input *SdksAndTools) isToolsZero() bool {
	return !input.Tools.Postman &&
		input.Tools.PostmanUrl == "" &&
		!input.Tools.Openapi &&
		input.Tools.OpenapiUrl == "" &&
		input.Tools.SwaggerUrl == "" &&
		!input.Tools.Insomnia &&
		input.Tools.InsomniaUrl == ""
}

func (input *SdksAndTools) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Sdks.OfficialCount)
	var1 := strconv.Itoa(input.Sdks.CommunityCount)
	length := 0
	if input.Sdks.Available {
		length += 30
		if input.Sdks.OfficialCount != 0 {
			length += 20
			length += len(var0)
			length += 13
			if input.Sdks.Javascript {
				length += 48
				length += len(input.Sdks.JsPackage)
				length += 48
				length += len(input.Sdks.JsDocs)
				length += 15
				length += len(input.Sdks.JsVersion)
				length += 18
				length += len(input.Sdks.JsSize)
				length += 1
			}
			length += 2
			if input.Sdks.Python {
				length += 33
				length += len(input.Sdks.PythonPackage)
				length += 44
				length += len(input.Sdks.PythonDocs)
				length += 15
				length += len(input.Sdks.PythonVersion)
				length += 27
				length += len(input.Sdks.PythonCompat)
				length += 1
			}
			length += 2
			if input.Sdks.Go {
				length += 24
				length += len(input.Sdks.GoPackage)
				length += 40
				length += len(input.Sdks.GoDocs)
				length += 15
				length += len(input.Sdks.GoVersion)
				length += 17
				length += len(input.Sdks.GoCompat)
				length += 1
			}
			length += 2
			if input.Sdks.Ruby {
				length += 31
				length += len(input.Sdks.RubyPackage)
				length += 42
				length += len(input.Sdks.RubyDocs)
				length += 15
				length += len(input.Sdks.RubyVersion)
				length += 1
			}
			length += 1
		}
		length += 2
		if input.Sdks.CommunityCount != 0 {
			length += 21
			length += len(var1)
			length += 12
			length += len(input.Sdks.CommunityList)
			length += 84
		}
		length += 1
	}
	length += 29
	if input.Tools.Postman {
		length += 90
		length += len(input.Tools.PostmanUrl)
		length += 107
	}
	length += 2
	if input.Tools.Openapi {
		length += 60
		length += len(input.Tools.OpenapiUrl)
		length += 46
		length += len(input.Tools.SwaggerUrl)
		length += 2
	}
	length += 2
	if input.Tools.Insomnia {
		length += 66
		length += len(input.Tools.InsomniaUrl)
		length += 2
	}
	b.Grow(length)
	if input.Sdks.Available {
		b.WriteString("\n## 🛠️ SDKs & Libraries\n\n")
		if input.Sdks.OfficialCount != 0 {
			b.WriteString("\n### Official SDKs (")
			b.WriteString(var0)
			b.WriteString(" languages)\n\n")
			if input.Sdks.Javascript {
				b.WriteString("\n#### JavaScript/TypeScript\n```bash\nnpm install ")
				b.WriteString(input.Sdks.JsPackage)
				b.WriteString("\n```\n\n**Documentation**: [JavaScript SDK Guide](")
				b.WriteString(input.Sdks.JsDocs)
				b.WriteString(")\n**Version**: ")
				b.WriteString(input.Sdks.JsVersion)
				b.WriteString("\n**Bundle Size**: ")
				b.WriteString(input.Sdks.JsSize)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n")
			if input.Sdks.Python {
				b.WriteString("\n#### Python\n```bash\npip install ")
				b.WriteString(input.Sdks.PythonPackage)
				b.WriteString("\n```\n\n**Documentation**: [Python SDK Guide](")
				b.WriteString(input.Sdks.PythonDocs)
				b.WriteString(")\n**Version**: ")
				b.WriteString(input.Sdks.PythonVersion)
				b.WriteString("\n**Python Compatibility**: ")
				b.WriteString(input.Sdks.PythonCompat)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n")
			if input.Sdks.Go {
				b.WriteString("\n#### Go\n```bash\ngo get ")
				b.WriteString(input.Sdks.GoPackage)
				b.WriteString("\n```\n\n**Documentation**: [Go SDK Guide](")
				b.WriteString(input.Sdks.GoDocs)
				b.WriteString(")\n**Version**: ")
				b.WriteString(input.Sdks.GoVersion)
				b.WriteString("\n**Go Version**: ")
				b.WriteString(input.Sdks.GoCompat)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n")
			if input.Sdks.Ruby {
				b.WriteString("\n#### Ruby\n```bash\ngem install ")
				b.WriteString(input.Sdks.RubyPackage)
				b.WriteString("\n```\n\n**Documentation**: [Ruby SDK Guide](")
				b.WriteString(input.Sdks.RubyDocs)
				b.WriteString(")\n**Version**: ")
				b.WriteString(input.Sdks.RubyVersion)
				b.WriteRune('\n')
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Sdks.CommunityCount != 0 {
			b.WriteString("\n### Community SDKs (")
			b.WriteString(var1)
			b.WriteString(" languages)\n")
			b.WriteString(input.Sdks.CommunityList)
			b.WriteString("\n\n*Note: Community SDKs are maintained by third parties and may not be up-to-date.*\n")
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🔧 Development Tools\n\n")
	if input.Tools.Postman {
		b.WriteString("\n### Postman Collection\nImport our complete API collection: [Download Postman Collection](")
		b.WriteString(input.Tools.PostmanUrl)
		b.WriteString(")\n\n**Features**:\n- Pre-configured environments\n- Authentication setup\n- Example requests for all endpoints\n")
	}
	b.WriteString("\n\n")
	if input.Tools.Openapi {
		b.WriteString("\n### OpenAPI Specification\n**OpenAPI 3.0**: [Download Spec](")
		b.WriteString(input.Tools.OpenapiUrl)
		b.WriteString(")\n**Swagger UI**: [Interactive Documentation](")
		b.WriteString(input.Tools.SwaggerUrl)
		b.WriteString(")\n")
	}
	b.WriteString("\n\n")
	if input.Tools.Insomnia {
		b.WriteString("\n### Insomnia Workspace\nImport for Insomnia: [Download Workspace](")
		b.WriteString(input.Tools.InsomniaUrl)
		b.WriteString(")\n")
	}
	return b.String()
}

type SupportAndResources struct {
	Support struct {
		HasPremium          bool
		PremiumResponseTime string
		PremiumEmail        string
		PremiumPhone        string
		PremiumSlack        string
		Discord             string
		StackoverflowTag    string
		GithubIssues        string
		StatusPage          bool
		StatusUrl           string
		SlaUptime           string
		CurrentStatus       string
	}
	Docs struct {
		TutorialsUrl     string
		BestPracticesUrl string
		ChangelogUrl     string
		Version          string
		LastUpdated      string
	}
	Api struct {
		Version string
	}
	Company struct {
		Name string
	}
}

func (input *SupportAndResources) isSupportZero() bool {
	return !input.Support.HasPremium &&
		input.Support.PremiumResponseTime == "" &&
		input.Support.PremiumEmail == "" &&
		input.Support.PremiumPhone == "" &&
		input.Support.PremiumSlack == "" &&
		input.Support.Discord == "" &&
		input.Support.StackoverflowTag == "" &&
		input.Support.GithubIssues == "" &&
		!input.Support.StatusPage &&
		input.Support.StatusUrl == "" &&
		input.Support.SlaUptime == "" &&
		input.Support.CurrentStatus == ""
}

func (input *SupportAndResources) isDocsZero() bool {
	return input.Docs.TutorialsUrl == "" &&
		input.Docs.BestPracticesUrl == "" &&
		input.Docs.ChangelogUrl == "" &&
		input.Docs.Version == "" &&
		input.Docs.LastUpdated == ""
}

func (input *SupportAndResources) isApiZero() bool {
	return input.Api.Version == ""
}

func (input *SupportAndResources) isCompanyZero() bool {
	return input.Company.Name == ""
}

func (input *SupportAndResources) String() string {
	var b strings.Builder
	length := 0
	length += 43
	if input.Support.HasPremium {
		length += 22
		length += len(input.Support.PremiumResponseTime)
		length += 24
		length += len(input.Support.PremiumEmail)
		length += 10
		length += len(input.Support.PremiumPhone)
		length += 10
		length += len(input.Support.PremiumSlack)
		length += 1
	}
	length += 36
	length += len(input.Support.Discord)
	length += 29
	length += len(input.Support.StackoverflowTag)
	length += 19
	length += len(input.Support.GithubIssues)
	length += 92
	length += len(input.Docs.TutorialsUrl)
	length += 23
	length += len(input.Docs.BestPracticesUrl)
	length += 18
	length += len(input.Docs.ChangelogUrl)
	length += 2
	if input.Support.StatusPage {
		length += 46
		length += len(input.Support.StatusUrl)
		length += 11
		length += len(input.Support.SlaUptime)
		length += 21
		length += len(input.Support.CurrentStatus)
		length += 1
	}
	length += 33
	length += len(input.Docs.Version)
	length += 19
	length += len(input.Docs.LastUpdated)
	length += 18
	length += len(input.Api.Version)
	length += 28
	length += len(input.Company.Name)
	length += 11
	b.Grow(length)
	b.WriteString("## 🆘 Getting Help\n\n### Support Channels\n")
	if input.Support.HasPremium {
		b.WriteString("\n**Premium Support**: ")
		b.WriteString(input.Support.PremiumResponseTime)
		b.WriteString(" response time\n- Email: ")
		b.WriteString(input.Support.PremiumEmail)
		b.WriteString("\n- Phone: ")
		b.WriteString(input.Support.PremiumPhone)
		b.WriteString("\n- Slack: ")
		b.WriteString(input.Support.PremiumSlack)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n**Community Support**:\n- Discord: ")
	b.WriteString(input.Support.Discord)
	b.WriteString("\n- Stack Overflow: Tag with `")
	b.WriteString(input.Support.StackoverflowTag)
	b.WriteString("`\n- GitHub Issues: ")
	b.WriteString(input.Support.GithubIssues)
	b.WriteString("\n\n### Documentation Resources\n- **API Reference**: You're reading it! 📖\n- **Tutorials**: ")
	b.WriteString(input.Docs.TutorialsUrl)
	b.WriteString("\n- **Best Practices**: ")
	b.WriteString(input.Docs.BestPracticesUrl)
	b.WriteString("\n- **Changelog**: ")
	b.WriteString(input.Docs.ChangelogUrl)
	b.WriteString("\n\n")
	if input.Support.StatusPage {
		b.WriteString("\n### Service Status\nCheck our service status: ")
		b.WriteString(input.Support.StatusUrl)
		b.WriteString("\n\n**SLA**: ")
		b.WriteString(input.Support.SlaUptime)
		b.WriteString("% uptime\n**Status**: ")
		b.WriteString(input.Support.CurrentStatus)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n---\n**Documentation Version**: ")
	b.WriteString(input.Docs.Version)
	b.WriteString("\n**Last Updated**: ")
	b.WriteString(input.Docs.LastUpdated)
	b.WriteString("\n**API Version**: ")
	b.WriteString(input.Api.Version)
	b.WriteString("\n\n*Built with ❤️ by the ")
	b.WriteString(input.Company.Name)
	b.WriteString(" API Team* ")
	return b.String()
}
