// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package kind

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unset-0]
	_ = x[EndTag-1]
	_ = x[OptionalBlock-2]
	_ = x[ElseBlock-3]
	_ = x[Title-4]
	_ = x[Text-5]
	_ = x[Var-6]
	_ = x[RawBlock-7]
}

const _Kind_name = "UnsetEndTagOptionalBlockElseBlockTitleTextVarRawBlock"

var _Kind_index = [...]uint8{0, 5, 11, 24, 33, 38, 42, 45, 53}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
