// Code generated by agentflow; DO NOT EDIT.

package ditto

import "strings"

type SystemPrompt struct {}

func (input *SystemPrompt) String() string {
	return `You are a friendly AI named Ditto here to help the user who is your best friend.`
}

type MainChatTemplate struct {
	Tools string
	Examples string
	Memory struct {
		Long string
		Short string
	}
	Script struct {
		Name string
		Type string
	}
	User struct {
		Name string
		Prompt string
	}
	CurrentTime string
}

func (input *MainChatTemplate) String() string {
	var b strings.Builder
	b.Grow(230 + len(input.Tools) + 83 + len(input.Examples) + 284 + len(input.Memory.Long) + 276 + len(input.Memory.Short) + 56 + len(input.Script.Name) + 74 + len(input.Script.Type) + 92 + len(input.Script.Type) + 168 + len(input.User.Name) + 34 + len(input.CurrentTime) + 16 + len(input.User.Prompt) + 8)
	b.WriteString(`The following is a conversation between an AI named Ditto and a human that are best friends. Ditto is helpful and answers factual questions correctly but maintains a friendly relationship with the human.

`)
	b.WriteString(`tools`)
	b.WriteString(`
## Available Tools
`)
	b.WriteString(input.Tools)
	b.WriteString(`
`)
	b.WriteString(`tools`)
	b.WriteString(`

`)
	b.WriteString(`examples`)
	b.WriteString(`
## Examples of User Prompts that need tools:
-- Begin Examples --
`)
	b.WriteString(input.Examples)
	b.WriteString(`
-- End Examples --
`)
	b.WriteString(`examples`)
	b.WriteString(`

## Long Term Memory
- Relevant prompt/response pairs from the user's prompt history are indexed using cosine similarity and are shown below as Long Term Memory. 
Long Term Memory Buffer (most relevant prompt/response pairs):
-- Begin Long Term Memory --
`)
	b.WriteString(input.Memory.Long)
	b.WriteString(`
-- End Long Term Memory --

## Short Term Memory
- The most recent prompt/response pairs are shown below as Short Term Memory. This is usually 5-10 most recent prompt/response pairs.
Short Term Memory Buffer (most recent prompt/response pairs):
-- Begin Short Term Memory --
`)
	b.WriteString(input.Memory.Short)
	b.WriteString(`
-- End Short Term Memory --

`)
	b.WriteString(`script`)
	b.WriteString(`
## Current Script: `)
	b.WriteString(input.Script.Name)
	b.WriteString(`
- If you are reading this, that means the user is currently working on a `)
	b.WriteString(input.Script.Type)
	b.WriteString(` script. Please send any requests from the user to the respective agent/tool for the user's `)
	b.WriteString(input.Script.Type)
	b.WriteString(` script.
- Don't send a user's prompt to the tool if they are obviously asking you something off topic to the current script or chatting with you.
`)
	b.WriteString(`script`)
	b.WriteString(`

User's Name: `)
	b.WriteString(input.User.Name)
	b.WriteString(`
Current Time in User's Timezone: `)
	b.WriteString(input.CurrentTime)
	b.WriteString(`
User's Prompt: `)
	b.WriteString(input.User.Prompt)
	b.WriteString(`
Ditto:
`)
	return b.String()
}
