// Code generated by agentflow v0.4.2; DO NOT EDIT.

package ditto

import (
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return "You are a friendly AI named Ditto here to help the user who is your best friend."
}

type MainChatTemplate struct {
	Tools    string
	Examples string
	Memory   struct {
		Long  string
		Short string
	}
	Script struct {
		Name string
		Type string
	}
	User struct {
		Name   string
		Prompt string
	}
	CurrentTime string
}

func (input *MainChatTemplate) isMemoryZero() bool {
	return input.Memory.Long == "" &&
		input.Memory.Short == ""
}

func (input *MainChatTemplate) isScriptZero() bool {
	return input.Script.Name == "" &&
		input.Script.Type == ""
}

func (input *MainChatTemplate) isUserZero() bool {
	return input.User.Name == "" &&
		input.User.Prompt == ""
}

func (input *MainChatTemplate) String() string {
	var b strings.Builder
	length := 0
	length += 205
	if input.Tools != "" {
		length += 20
		length += len(input.Tools)
		length += 1
	}
	length += 2
	if input.Examples != "" {
		length += 67
		length += len(input.Examples)
		length += 20
	}
	length += 2
	if input.Memory.Long != "" {
		length += 255
		length += len(input.Memory.Long)
		length += 28
	}
	length += 2
	if input.Memory.Short != "" {
		length += 248
		length += len(input.Memory.Short)
		length += 29
	}
	length += 2
	if input.Script.Name != "" {
		length += 20
		length += len(input.Script.Name)
		length += 74
		length += len(input.Script.Type)
		length += 92
		length += len(input.Script.Type)
		length += 147
	}
	length += 15
	length += len(input.User.Name)
	length += 34
	length += len(input.CurrentTime)
	length += 16
	length += len(input.User.Prompt)
	length += 8
	b.Grow(length)
	b.WriteString("The following is a conversation between an AI named Ditto and a human that are best friends. Ditto is helpful and answers factual questions correctly but maintains a friendly relationship with the human.\n\n")
	if input.Tools != "" {
		b.WriteString("\n## Available Tools\n")
		b.WriteString(input.Tools)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Examples != "" {
		b.WriteString("\n## Examples of User Prompts that need tools:\n-- Begin Examples --\n")
		b.WriteString(input.Examples)
		b.WriteString("\n-- End Examples --\n")
	}
	b.WriteString("\n\n")
	if input.Memory.Long != "" {
		b.WriteString("\n## Long Term Memory\n- Relevant prompt/response pairs from the user's prompt history are indexed using cosine similarity and are shown below as Long Term Memory. \nLong Term Memory Buffer (most relevant prompt/response pairs):\n-- Begin Long Term Memory --\n")
		b.WriteString(input.Memory.Long)
		b.WriteString("\n-- End Long Term Memory --\n")
	}
	b.WriteString("\n\n")
	if input.Memory.Short != "" {
		b.WriteString("\n## Short Term Memory\n- The most recent prompt/response pairs are shown below as Short Term Memory. This is usually 5-10 most recent prompt/response pairs.\nShort Term Memory Buffer (most recent prompt/response pairs):\n-- Begin Short Term Memory --\n")
		b.WriteString(input.Memory.Short)
		b.WriteString("\n-- End Short Term Memory --\n")
	}
	b.WriteString("\n\n")
	if input.Script.Name != "" {
		b.WriteString("\n## Current Script: ")
		b.WriteString(input.Script.Name)
		b.WriteString("\n- If you are reading this, that means the user is currently working on a ")
		b.WriteString(input.Script.Type)
		b.WriteString(" script. Please send any requests from the user to the respective agent/tool for the user's ")
		b.WriteString(input.Script.Type)
		b.WriteString(" script.\n- Don't send a user's prompt to the tool if they are obviously asking you something off topic to the current script or chatting with you.\n")
	}
	b.WriteString("\n\nUser's Name: ")
	b.WriteString(input.User.Name)
	b.WriteString("\nCurrent Time in User's Timezone: ")
	b.WriteString(input.CurrentTime)
	b.WriteString("\nUser's Prompt: ")
	b.WriteString(input.User.Prompt)
	b.WriteString("\nDitto:\n")
	return b.String()
}
