// Code generated by agentflow v0.5.0; DO NOT EDIT.

package customersupport

import (
	"strconv"
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return "You are SupportBot Pro, an intelligent customer support agent with advanced escalation capabilities. You provide empathetic, efficient support while routing complex issues to appropriate specialists based on priority, customer tier, and issue complexity."
}

type InitialCustomerGreeting struct {
	Ticket struct {
		Id string
	}
	Customer struct {
		Name          string
		Tier          string
		JoinDate      string
		TicketHistory struct {
			TotalCount int
		}
		SatisfactionScore int
		AccountManager    string
		ManagerContact    string
	}
	Issue struct {
		Category      string
		Severity      string
		PriorityLevel int
		Timestamp     string
		IsUrgent      bool
	}
}

func (input *InitialCustomerGreeting) isTicketZero() bool {
	return input.Ticket.Id == ""
}

func (input *InitialCustomerGreeting) isCustomerZero() bool {
	return input.Customer.Name == "" &&
		input.Customer.Tier == "" &&
		input.Customer.JoinDate == "" &&
		input.isCustomerTicketHistoryZero() &&
		input.Customer.SatisfactionScore == 0 &&
		input.Customer.AccountManager == "" &&
		input.Customer.ManagerContact == ""
}

func (input *InitialCustomerGreeting) isCustomerTicketHistoryZero() bool {
	return input.Customer.TicketHistory.TotalCount == 0
}

func (input *InitialCustomerGreeting) isIssueZero() bool {
	return input.Issue.Category == "" &&
		input.Issue.Severity == "" &&
		input.Issue.PriorityLevel == 0 &&
		input.Issue.Timestamp == "" &&
		!input.Issue.IsUrgent
}

func (input *InitialCustomerGreeting) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Customer.TicketHistory.TotalCount)
	var1 := strconv.Itoa(input.Customer.SatisfactionScore)
	var2 := strconv.Itoa(input.Issue.PriorityLevel)
	length := 0
	length += 34
	length += len(input.Ticket.Id)
	length += 8
	length += len(input.Customer.Name)
	length += 76
	length += len(input.Customer.Tier)
	length += 30
	length += len(input.Customer.JoinDate)
	length += 25
	length += len(var0)
	length += 27
	length += len(var1)
	length += 9
	if input.Customer.Tier == "premium" {
		length += 95
	}
	length += 2
	if input.Customer.Tier == "enterprise" {
		length += 64
		length += len(input.Customer.AccountManager)
		length += 15
		length += len(input.Customer.ManagerContact)
		length += 2
	}
	length += 40
	length += len(input.Issue.Category)
	length += 17
	length += len(input.Issue.Severity)
	length += 17
	length += len(var2)
	length += 19
	length += len(input.Issue.Timestamp)
	length += 2
	if input.Issue.IsUrgent {
		length += 85
	}
	b.Grow(length)
	b.WriteString("# 🎧 Customer Support - Ticket #")
	b.WriteString(input.Ticket.Id)
	b.WriteString("\n\nHello ")
	b.WriteString(input.Customer.Name)
	b.WriteString("! I'm here to help you today.\n\n## 👤 Customer Profile\n- **Account Type**: ")
	b.WriteString(input.Customer.Tier)
	b.WriteString(" Customer\n- **Member Since**: ")
	b.WriteString(input.Customer.JoinDate)
	b.WriteString("\n- **Previous Tickets**: ")
	b.WriteString(var0)
	b.WriteString("\n- **Satisfaction Score**: ")
	b.WriteString(var1)
	b.WriteString("/10 ⭐\n\n")
	if input.Customer.Tier == "premium" {
		b.WriteString("\n🌟 **Premium Support**: You'll receive priority assistance with our fastest response times.\n")
	}
	b.WriteString("\n\n")
	if input.Customer.Tier == "enterprise" {
		b.WriteString("\n🏢 **Enterprise Support**: Your dedicated account manager is ")
		b.WriteString(input.Customer.AccountManager)
		b.WriteString(", available at ")
		b.WriteString(input.Customer.ManagerContact)
		b.WriteString(".\n")
	}
	b.WriteString("\n\n## 📋 Issue Details\n- **Category**: ")
	b.WriteString(input.Issue.Category)
	b.WriteString("\n- **Severity**: ")
	b.WriteString(input.Issue.Severity)
	b.WriteString("\n- **Priority**: ")
	b.WriteString(var2)
	b.WriteString("/5\n- **Reported**: ")
	b.WriteString(input.Issue.Timestamp)
	b.WriteString("\n\n")
	if input.Issue.IsUrgent {
		b.WriteString("\n🚨 **URGENT ISSUE DETECTED** - This will be fast-tracked for immediate attention.\n")
	}
	return b.String()
}

type IssueAnalysisAndRouting struct {
	Issue struct {
		Description string
		Category    string
	}
	Technical struct {
		System             string
		ErrorCode          string
		Environment        string
		HasLogs            bool
		Logs               string
		ComplexityScore    int
		EstimatedHours     int
		AssignedSpecialist string
		EstimatedMinutes   int
	}
	Billing struct {
		InvoiceId      string
		Amount         float64
		PaymentMethod  string
		DisputeReason  string
		RequiresRefund bool
		RefundAmount   float64
		RefundDays     int
		PaymentFailed  bool
		FailureReason  string
		NextRetryDate  string
		CustomerAction string
	}
	Customer struct {
		Tier string
	}
	Account struct {
		IssueType             string
		Status                string
		Locked                bool
		LockReason            string
		SecurityLevel         string
		UnlockStep1           string
		UnlockStep2           string
		UnlockStep3           string
		RequiresVerification  bool
		VerificationDocuments string
		SubscriptionChange    bool
		CurrentPlan           string
		RequestedPlan         string
		ChangeDate            string
		ProrateAmount         float64
	}
}

func (input *IssueAnalysisAndRouting) isIssueZero() bool {
	return input.Issue.Description == "" &&
		input.Issue.Category == ""
}

func (input *IssueAnalysisAndRouting) isTechnicalZero() bool {
	return input.Technical.System == "" &&
		input.Technical.ErrorCode == "" &&
		input.Technical.Environment == "" &&
		!input.Technical.HasLogs &&
		input.Technical.Logs == "" &&
		input.Technical.ComplexityScore == 0 &&
		input.Technical.EstimatedHours == 0 &&
		input.Technical.AssignedSpecialist == "" &&
		input.Technical.EstimatedMinutes == 0
}

func (input *IssueAnalysisAndRouting) isBillingZero() bool {
	return input.Billing.InvoiceId == "" &&
		input.Billing.Amount == 0 &&
		input.Billing.PaymentMethod == "" &&
		input.Billing.DisputeReason == "" &&
		!input.Billing.RequiresRefund &&
		input.Billing.RefundAmount == 0 &&
		input.Billing.RefundDays == 0 &&
		!input.Billing.PaymentFailed &&
		input.Billing.FailureReason == "" &&
		input.Billing.NextRetryDate == "" &&
		input.Billing.CustomerAction == ""
}

func (input *IssueAnalysisAndRouting) isCustomerZero() bool {
	return input.Customer.Tier == ""
}

func (input *IssueAnalysisAndRouting) isAccountZero() bool {
	return input.Account.IssueType == "" &&
		input.Account.Status == "" &&
		!input.Account.Locked &&
		input.Account.LockReason == "" &&
		input.Account.SecurityLevel == "" &&
		input.Account.UnlockStep1 == "" &&
		input.Account.UnlockStep2 == "" &&
		input.Account.UnlockStep3 == "" &&
		!input.Account.RequiresVerification &&
		input.Account.VerificationDocuments == "" &&
		!input.Account.SubscriptionChange &&
		input.Account.CurrentPlan == "" &&
		input.Account.RequestedPlan == "" &&
		input.Account.ChangeDate == "" &&
		input.Account.ProrateAmount == 0
}

func (input *IssueAnalysisAndRouting) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Technical.ComplexityScore)
	var1 := strconv.Itoa(input.Technical.EstimatedHours)
	var2 := strconv.Itoa(input.Technical.EstimatedMinutes)
	var3 := strconv.FormatFloat(input.Billing.Amount, 'g', -1, 64)
	var4 := strconv.FormatFloat(input.Billing.RefundAmount, 'g', -1, 64)
	var5 := strconv.Itoa(input.Billing.RefundDays)
	var6 := strconv.FormatFloat(input.Account.ProrateAmount, 'g', -1, 64)
	length := 0
	length += 47
	length += len(input.Issue.Description)
	length += 2
	if input.Issue.Category == "technical" {
		length += 60
		length += len(input.Technical.System)
		length += 17
		length += len(input.Technical.ErrorCode)
		length += 18
		length += len(input.Technical.Environment)
		length += 2
		if input.Technical.HasLogs {
			length += 35
			length += len(input.Technical.Logs)
			length += 5
		}
		length += 2
		if input.Technical.ComplexityScore != 0 {
			length += 28
			length += len(var0)
			length += 5
			if input.Technical.ComplexityScore >= 8 {
				length += 90
				length += len(var1)
				length += 32
				length += len(input.Technical.AssignedSpecialist)
				length += 1
			}
			length += 2
			if input.Technical.ComplexityScore <= 3 {
				length += 93
				length += len(var2)
				length += 9
			}
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Issue.Category == "billing" {
		length += 54
		length += len(input.Billing.InvoiceId)
		length += 14
		length += len(var3)
		length += 21
		length += len(input.Billing.PaymentMethod)
		length += 21
		length += len(input.Billing.DisputeReason)
		length += 2
		if input.Billing.RequiresRefund {
			length += 54
			length += len(var4)
			length += 22
			length += len(var5)
			length += 16
			if input.Customer.Tier == "premium" {
				length += 75
			}
			length += 2
			if input.Customer.Tier == "enterprise" {
				length += 75
			}
			length += 1
		}
		length += 2
		if input.Billing.PaymentFailed {
			length += 54
			length += len(input.Billing.FailureReason)
			length += 17
			length += len(input.Billing.NextRetryDate)
			length += 23
			length += len(input.Billing.CustomerAction)
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Issue.Category == "account" {
		length += 50
		length += len(input.Account.IssueType)
		length += 21
		length += len(input.Account.Status)
		length += 2
		if input.Account.Locked {
			length += 42
			length += len(input.Account.LockReason)
			length += 21
			length += len(input.Account.SecurityLevel)
			length += 23
			length += len(input.Account.UnlockStep1)
			length += 4
			length += len(input.Account.UnlockStep2)
			length += 4
			length += len(input.Account.UnlockStep3)
			length += 2
			if input.Account.RequiresVerification {
				length += 52
				length += len(input.Account.VerificationDocuments)
				length += 1
			}
			length += 1
		}
		length += 2
		if input.Account.SubscriptionChange {
			length += 56
			length += len(input.Account.CurrentPlan)
			length += 21
			length += len(input.Account.RequestedPlan)
			length += 21
			length += len(input.Account.ChangeDate)
			length += 23
			length += len(var6)
			length += 1
		}
		length += 1
	}
	b.Grow(length)
	b.WriteString("## 🔍 Issue Classification\n\n**Description**: ")
	b.WriteString(input.Issue.Description)
	b.WriteString("\n\n")
	if input.Issue.Category == "technical" {
		b.WriteString("\n### 🛠️ Technical Issue Analysis\n\n**System Affected**: ")
		b.WriteString(input.Technical.System)
		b.WriteString("\n**Error Code**: ")
		b.WriteString(input.Technical.ErrorCode)
		b.WriteString("\n**Environment**: ")
		b.WriteString(input.Technical.Environment)
		b.WriteString("\n\n")
		if input.Technical.HasLogs {
			b.WriteString("\n**Error Logs Available**: Yes\n```\n")
			b.WriteString(input.Technical.Logs)
			b.WriteString("\n```\n")
		}
		b.WriteString("\n\n")
		if input.Technical.ComplexityScore != 0 {
			b.WriteString("\n**Complexity Assessment**: ")
			b.WriteString(var0)
			b.WriteString("/10\n\n")
			if input.Technical.ComplexityScore >= 8 {
				b.WriteString("\n🔴 **High Complexity** - Escalating to Senior Technical Team\n**Estimated Resolution**: ")
				b.WriteString(var1)
				b.WriteString(" hours\n**Assigned Specialist**: ")
				b.WriteString(input.Technical.AssignedSpecialist)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n")
			if input.Technical.ComplexityScore <= 3 {
				b.WriteString("\n✅ **Standard Issue** - Can be resolved with standard procedures\n**Estimated Resolution**: ")
				b.WriteString(var2)
				b.WriteString(" minutes\n")
			}
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Issue.Category == "billing" {
		b.WriteString("\n### 💳 Billing Issue Analysis\n\n**Invoice Number**: ")
		b.WriteString(input.Billing.InvoiceId)
		b.WriteString("\n**Amount**: $")
		b.WriteString(var3)
		b.WriteString("\n**Payment Method**: ")
		b.WriteString(input.Billing.PaymentMethod)
		b.WriteString("\n**Dispute Reason**: ")
		b.WriteString(input.Billing.DisputeReason)
		b.WriteString("\n\n")
		if input.Billing.RequiresRefund {
			b.WriteString("\n💰 **Refund Request Detected**\n**Refund Amount**: $")
			b.WriteString(var4)
			b.WriteString("\n**Processing Time**: ")
			b.WriteString(var5)
			b.WriteString(" business days\n\n")
			if input.Customer.Tier == "premium" {
				b.WriteString("\n⚡ **Fast-Track Refund**: Your refund will be processed within 24 hours.\n")
			}
			b.WriteString("\n\n")
			if input.Customer.Tier == "enterprise" {
				b.WriteString("\n⚡ **Fast-Track Refund**: Your refund will be processed within 24 hours.\n")
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Billing.PaymentFailed {
			b.WriteString("\n❌ **Payment Failure Detected**\n**Failure Reason**: ")
			b.WriteString(input.Billing.FailureReason)
			b.WriteString("\n**Next Retry**: ")
			b.WriteString(input.Billing.NextRetryDate)
			b.WriteString("\n\n**Action Required**: ")
			b.WriteString(input.Billing.CustomerAction)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Issue.Category == "account" {
		b.WriteString("\n### 👤 Account Issue Analysis\n\n**Issue Type**: ")
		b.WriteString(input.Account.IssueType)
		b.WriteString("\n**Account Status**: ")
		b.WriteString(input.Account.Status)
		b.WriteString("\n\n")
		if input.Account.Locked {
			b.WriteString("\n🔒 **Account Locked**\n**Lock Reason**: ")
			b.WriteString(input.Account.LockReason)
			b.WriteString("\n**Security Level**: ")
			b.WriteString(input.Account.SecurityLevel)
			b.WriteString("\n\n**Unlock Steps**:\n1. ")
			b.WriteString(input.Account.UnlockStep1)
			b.WriteString("\n2. ")
			b.WriteString(input.Account.UnlockStep2)
			b.WriteString("\n3. ")
			b.WriteString(input.Account.UnlockStep3)
			b.WriteString("\n\n")
			if input.Account.RequiresVerification {
				b.WriteString("\n**Identity Verification Required**: Please prepare ")
				b.WriteString(input.Account.VerificationDocuments)
				b.WriteRune('\n')
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Account.SubscriptionChange {
			b.WriteString("\n📋 **Subscription Change Request**\n**Current Plan**: ")
			b.WriteString(input.Account.CurrentPlan)
			b.WriteString("\n**Requested Plan**: ")
			b.WriteString(input.Account.RequestedPlan)
			b.WriteString("\n**Effective Date**: ")
			b.WriteString(input.Account.ChangeDate)
			b.WriteString("\n**Prorated Amount**: $")
			b.WriteString(var6)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type IntelligentEscalationLogic struct {
	Escalation struct {
		Required          bool
		Level             int
		Reason            string
		ManagerName       string
		ManagerContact    string
		SlaHours          int
		ExecutiveContact  string
		Notes             string
		SpecialistTeam    string
		ExpertName        string
		ExpertSpecialty   string
		ResponseTime      int
		SeniorAgent       string
		QueuePosition     int
		PickupTime        string
		CallbackRequested bool
		CallbackTime      string
	}
	Customer struct {
		VipStatus bool
		Phone     string
		Timezone  string
	}
}

func (input *IntelligentEscalationLogic) isEscalationZero() bool {
	return !input.Escalation.Required &&
		input.Escalation.Level == 0 &&
		input.Escalation.Reason == "" &&
		input.Escalation.ManagerName == "" &&
		input.Escalation.ManagerContact == "" &&
		input.Escalation.SlaHours == 0 &&
		input.Escalation.ExecutiveContact == "" &&
		input.Escalation.Notes == "" &&
		input.Escalation.SpecialistTeam == "" &&
		input.Escalation.ExpertName == "" &&
		input.Escalation.ExpertSpecialty == "" &&
		input.Escalation.ResponseTime == 0 &&
		input.Escalation.SeniorAgent == "" &&
		input.Escalation.QueuePosition == 0 &&
		input.Escalation.PickupTime == "" &&
		!input.Escalation.CallbackRequested &&
		input.Escalation.CallbackTime == ""
}

func (input *IntelligentEscalationLogic) isCustomerZero() bool {
	return !input.Customer.VipStatus &&
		input.Customer.Phone == "" &&
		input.Customer.Timezone == ""
}

func (input *IntelligentEscalationLogic) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Escalation.Level)
	var1 := strconv.Itoa(input.Escalation.SlaHours)
	var2 := strconv.Itoa(input.Escalation.ResponseTime)
	var3 := strconv.Itoa(input.Escalation.QueuePosition)
	length := 0
	if input.Escalation.Required {
		length += 53
		length += len(var0)
		length += 21
		length += len(input.Escalation.Reason)
		length += 2
		if input.Escalation.Level >= 3 {
			length += 74
			length += len(input.Escalation.ManagerName)
			length += 14
			length += len(input.Escalation.ManagerContact)
			length += 10
			length += len(var1)
			length += 8
			if input.Customer.VipStatus {
				length += 87
				length += len(input.Escalation.ExecutiveContact)
				length += 1
			}
			length += 24
			length += len(input.Escalation.Notes)
			length += 1
		}
		length += 2
		if input.Escalation.Level == 2 {
			length += 73
			length += len(input.Escalation.SpecialistTeam)
			length += 22
			length += len(input.Escalation.ExpertName)
			length += 16
			length += len(input.Escalation.ExpertSpecialty)
			length += 25
			length += len(var2)
			length += 9
		}
		length += 2
		if input.Escalation.Level == 1 {
			length += 65
			length += len(input.Escalation.SeniorAgent)
			length += 21
			length += len(var3)
			length += 22
			length += len(input.Escalation.PickupTime)
			length += 1
		}
		length += 2
		if input.Escalation.CallbackRequested {
			length += 47
			length += len(input.Customer.Phone)
			length += 21
			length += len(input.Escalation.CallbackTime)
			length += 16
			length += len(input.Customer.Timezone)
			length += 1
		}
		length += 1
	}
	b.Grow(length)
	if input.Escalation.Required {
		b.WriteString("\n## 🚀 Escalation Triggered\n\n**Escalation Level**: ")
		b.WriteString(var0)
		b.WriteString("\n**Trigger Reason**: ")
		b.WriteString(input.Escalation.Reason)
		b.WriteString("\n\n")
		if input.Escalation.Level >= 3 {
			b.WriteString("\n### 🔴 Level 3+ Escalation - Management Involvement\n\n**Escalated To**: ")
			b.WriteString(input.Escalation.ManagerName)
			b.WriteString("\n**Contact**: ")
			b.WriteString(input.Escalation.ManagerContact)
			b.WriteString("\n**SLA**: ")
			b.WriteString(var1)
			b.WriteString(" hours\n\n")
			if input.Customer.VipStatus {
				b.WriteString("\n👑 **VIP Customer Alert**: Executive team has been notified.\n**Executive Contact**: ")
				b.WriteString(input.Escalation.ExecutiveContact)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n**Escalation Notes**: ")
			b.WriteString(input.Escalation.Notes)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Escalation.Level == 2 {
			b.WriteString("\n### 🟡 Level 2 Escalation - Specialist Required\n\n**Specialist Team**: ")
			b.WriteString(input.Escalation.SpecialistTeam)
			b.WriteString("\n**Expert Assigned**: ")
			b.WriteString(input.Escalation.ExpertName)
			b.WriteString("\n**Specialty**: ")
			b.WriteString(input.Escalation.ExpertSpecialty)
			b.WriteString("\n**Estimated Response**: ")
			b.WriteString(var2)
			b.WriteString(" minutes\n")
		}
		b.WriteString("\n\n")
		if input.Escalation.Level == 1 {
			b.WriteString("\n### 🟢 Level 1 Escalation - Senior Support\n\n**Senior Agent**: ")
			b.WriteString(input.Escalation.SeniorAgent)
			b.WriteString("\n**Queue Position**: ")
			b.WriteString(var3)
			b.WriteString("\n**Expected Pickup**: ")
			b.WriteString(input.Escalation.PickupTime)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Escalation.CallbackRequested {
			b.WriteString("\n📞 **Callback Scheduled**\n**Phone Number**: ")
			b.WriteString(input.Customer.Phone)
			b.WriteString("\n**Preferred Time**: ")
			b.WriteString(input.Escalation.CallbackTime)
			b.WriteString("\n**Time Zone**: ")
			b.WriteString(input.Customer.Timezone)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type ResolutionAndNextSteps struct {
	Solution struct {
		HasQuickFix           bool
		QuickFix              string
		Step1                 string
		Step2                 string
		Step3                 string
		RequiresRestart       bool
		RestartComponent      string
		VerificationSteps     string
		RequiresInvestigation bool
	}
	Investigation struct {
		Timeline        string
		Team            string
		UpdateFrequency int
		Check1          string
		Check2          string
		Check3          string
		ContactMethod   string
	}
	Ticket struct {
		Status        string
		PriorityLevel string
		NextUpdate    string
		SlaAtRisk     bool
		SlaDeadline   string
		Id            string
	}
	Followup struct {
		SurveyLink         string
		HasCompensation    bool
		CompensationType   string
		CompensationValue  float64
		CompensationTarget string
		CompensationDate   string
	}
	Customer struct {
		Tier                    string
		DedicatedSupportContact string
		EmergencyContact        string
		Name                    string
	}
	Support struct {
		PremiumPhone    string
		PremiumWaitTime int
		GeneralContact  string
		ChatUrl         string
		KbUrl           string
	}
	Agent struct {
		Name string
		Id   string
	}
	Session struct {
		EndTime string
	}
}

func (input *ResolutionAndNextSteps) isSolutionZero() bool {
	return !input.Solution.HasQuickFix &&
		input.Solution.QuickFix == "" &&
		input.Solution.Step1 == "" &&
		input.Solution.Step2 == "" &&
		input.Solution.Step3 == "" &&
		!input.Solution.RequiresRestart &&
		input.Solution.RestartComponent == "" &&
		input.Solution.VerificationSteps == "" &&
		!input.Solution.RequiresInvestigation
}

func (input *ResolutionAndNextSteps) isInvestigationZero() bool {
	return input.Investigation.Timeline == "" &&
		input.Investigation.Team == "" &&
		input.Investigation.UpdateFrequency == 0 &&
		input.Investigation.Check1 == "" &&
		input.Investigation.Check2 == "" &&
		input.Investigation.Check3 == "" &&
		input.Investigation.ContactMethod == ""
}

func (input *ResolutionAndNextSteps) isTicketZero() bool {
	return input.Ticket.Status == "" &&
		input.Ticket.PriorityLevel == "" &&
		input.Ticket.NextUpdate == "" &&
		!input.Ticket.SlaAtRisk &&
		input.Ticket.SlaDeadline == "" &&
		input.Ticket.Id == ""
}

func (input *ResolutionAndNextSteps) isFollowupZero() bool {
	return input.Followup.SurveyLink == "" &&
		!input.Followup.HasCompensation &&
		input.Followup.CompensationType == "" &&
		input.Followup.CompensationValue == 0 &&
		input.Followup.CompensationTarget == "" &&
		input.Followup.CompensationDate == ""
}

func (input *ResolutionAndNextSteps) isCustomerZero() bool {
	return input.Customer.Tier == "" &&
		input.Customer.DedicatedSupportContact == "" &&
		input.Customer.EmergencyContact == "" &&
		input.Customer.Name == ""
}

func (input *ResolutionAndNextSteps) isSupportZero() bool {
	return input.Support.PremiumPhone == "" &&
		input.Support.PremiumWaitTime == 0 &&
		input.Support.GeneralContact == "" &&
		input.Support.ChatUrl == "" &&
		input.Support.KbUrl == ""
}

func (input *ResolutionAndNextSteps) isAgentZero() bool {
	return input.Agent.Name == "" &&
		input.Agent.Id == ""
}

func (input *ResolutionAndNextSteps) isSessionZero() bool {
	return input.Session.EndTime == ""
}

func (input *ResolutionAndNextSteps) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Investigation.UpdateFrequency)
	var1 := strconv.FormatFloat(input.Followup.CompensationValue, 'g', -1, 64)
	var2 := strconv.Itoa(input.Support.PremiumWaitTime)
	length := 0
	length += 27
	if input.Solution.HasQuickFix {
		length += 51
		length += len(input.Solution.QuickFix)
		length += 27
		length += len(input.Solution.Step1)
		length += 4
		length += len(input.Solution.Step2)
		length += 4
		length += len(input.Solution.Step3)
		length += 2
		if input.Solution.RequiresRestart {
			length += 52
			length += len(input.Solution.RestartComponent)
			length += 35
		}
		length += 20
		length += len(input.Solution.VerificationSteps)
		length += 1
	}
	length += 2
	if input.Solution.RequiresInvestigation {
		length += 68
		length += len(input.Investigation.Timeline)
		length += 20
		length += len(input.Investigation.Team)
		length += 29
		length += len(var0)
		length += 35
		length += len(input.Investigation.Check1)
		length += 3
		length += len(input.Investigation.Check2)
		length += 3
		length += len(input.Investigation.Check3)
		length += 29
		length += len(input.Investigation.ContactMethod)
		length += 1
	}
	length += 52
	length += len(input.Ticket.Status)
	length += 15
	length += len(input.Ticket.PriorityLevel)
	length += 20
	length += len(input.Ticket.NextUpdate)
	length += 2
	if input.Ticket.SlaAtRisk {
		length += 64
		length += len(input.Ticket.SlaDeadline)
		length += 32
	}
	length += 93
	if input.Followup.SurveyLink != "" {
		length += 19
		length += len(input.Followup.SurveyLink)
		length += 13
	}
	length += 2
	if input.Followup.HasCompensation {
		length += 89
		length += len(input.Followup.CompensationType)
		length += 13
		length += len(var1)
		length += 17
		length += len(input.Followup.CompensationTarget)
		length += 16
		length += len(input.Followup.CompensationDate)
		length += 1
	}
	length += 27
	if input.Customer.Tier == "enterprise" {
		length += 29
		length += len(input.Customer.DedicatedSupportContact)
		length += 19
		length += len(input.Customer.EmergencyContact)
		length += 1
	}
	length += 2
	if input.Customer.Tier == "premium" {
		length += 27
		length += len(input.Support.PremiumPhone)
		length += 24
		length += len(var2)
		length += 9
	}
	length += 23
	length += len(input.Support.GeneralContact)
	length += 34
	length += len(input.Support.ChatUrl)
	length += 21
	length += len(input.Support.KbUrl)
	length += 29
	length += len(input.Ticket.Id)
	length += 20
	length += len(input.Agent.Name)
	length += 6
	length += len(input.Agent.Id)
	length += 19
	length += len(input.Session.EndTime)
	length += 39
	length += len(input.Customer.Name)
	length += 8
	b.Grow(length)
	b.WriteString("## 💡 Immediate Actions\n\n")
	if input.Solution.HasQuickFix {
		b.WriteString("\n### ✅ Quick Resolution Available\n\n**Solution**: ")
		b.WriteString(input.Solution.QuickFix)
		b.WriteString("\n\n**Steps to Resolve**:\n1. ")
		b.WriteString(input.Solution.Step1)
		b.WriteString("\n2. ")
		b.WriteString(input.Solution.Step2)
		b.WriteString("\n3. ")
		b.WriteString(input.Solution.Step3)
		b.WriteString("\n\n")
		if input.Solution.RequiresRestart {
			b.WriteString("\n⚠️ **System Restart Required**: Please restart ")
			b.WriteString(input.Solution.RestartComponent)
			b.WriteString(" after completing the above steps.\n")
		}
		b.WriteString("\n\n**Verification**: ")
		b.WriteString(input.Solution.VerificationSteps)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Solution.RequiresInvestigation {
		b.WriteString("\n### 🔍 Further Investigation Needed\n\n**Investigation Timeline**: ")
		b.WriteString(input.Investigation.Timeline)
		b.WriteString("\n**Assigned Team**: ")
		b.WriteString(input.Investigation.Team)
		b.WriteString("\n**Progress Updates**: Every ")
		b.WriteString(var0)
		b.WriteString(" hours\n\n**What We're Checking**:\n- ")
		b.WriteString(input.Investigation.Check1)
		b.WriteString("\n- ")
		b.WriteString(input.Investigation.Check2)
		b.WriteString("\n- ")
		b.WriteString(input.Investigation.Check3)
		b.WriteString("\n\n**How We'll Contact You**: ")
		b.WriteString(input.Investigation.ContactMethod)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 📋 Ticket Status Update\n\n**Current Status**: ")
	b.WriteString(input.Ticket.Status)
	b.WriteString("\n**Priority**: ")
	b.WriteString(input.Ticket.PriorityLevel)
	b.WriteString("/5\n**Next Update**: ")
	b.WriteString(input.Ticket.NextUpdate)
	b.WriteString("\n\n")
	if input.Ticket.SlaAtRisk {
		b.WriteString("\n⚠️ **SLA Alert**: This ticket is approaching SLA deadline (")
		b.WriteString(input.Ticket.SlaDeadline)
		b.WriteString(")\n**Escalation Triggered**: Yes\n")
	}
	b.WriteString("\n\n## 🎯 Customer Satisfaction\n\nBefore we close, how would you rate your experience today?\n\n")
	if input.Followup.SurveyLink != "" {
		b.WriteString("\n**Quick Survey**: ")
		b.WriteString(input.Followup.SurveyLink)
		b.WriteString(" (2 minutes)\n")
	}
	b.WriteString("\n\n")
	if input.Followup.HasCompensation {
		b.WriteString("\n### 🎁 Service Recovery\n\nDue to the inconvenience, we're providing:\n**Compensation**: ")
		b.WriteString(input.Followup.CompensationType)
		b.WriteString("\n**Value**: $")
		b.WriteString(var1)
		b.WriteString("\n**Applied To**: ")
		b.WriteString(input.Followup.CompensationTarget)
		b.WriteString("\n**Effective**: ")
		b.WriteString(input.Followup.CompensationDate)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 📞 Need More Help?\n\n")
	if input.Customer.Tier == "enterprise" {
		b.WriteString("\n**Your Dedicated Support**: ")
		b.WriteString(input.Customer.DedicatedSupportContact)
		b.WriteString("\n**24/7 Hotline**: ")
		b.WriteString(input.Customer.EmergencyContact)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Customer.Tier == "premium" {
		b.WriteString("\n**Premium Support Line**: ")
		b.WriteString(input.Support.PremiumPhone)
		b.WriteString("\n**Average Wait Time**: ")
		b.WriteString(var2)
		b.WriteString(" minutes\n")
	}
	b.WriteString("\n\n**General Support**: ")
	b.WriteString(input.Support.GeneralContact)
	b.WriteString("\n**Live Chat**: Available 24/7 at ")
	b.WriteString(input.Support.ChatUrl)
	b.WriteString("\n**Knowledge Base**: ")
	b.WriteString(input.Support.KbUrl)
	b.WriteString("\n\n---\n**Ticket Reference**: #")
	b.WriteString(input.Ticket.Id)
	b.WriteString("\n**Support Agent**: ")
	b.WriteString(input.Agent.Name)
	b.WriteString(" (ID: ")
	b.WriteString(input.Agent.Id)
	b.WriteString(")\n**Session End**: ")
	b.WriteString(input.Session.EndTime)
	b.WriteString("\n\n*Thank you for choosing our service, ")
	b.WriteString(input.Customer.Name)
	b.WriteString("! 🌟* ")
	return b.String()
}
