// Code generated by agentflow v0.5.1; DO NOT EDIT.

package learningassistant

import (
	"strconv"
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return "You are AdaptiveTutor, an AI learning assistant that personalizes education based on student progress, learning style, and current skill level. You provide engaging, interactive lessons with appropriate difficulty scaling."
}

type LessonIntroduction struct {
	Subject string
	Student struct {
		Name                 string
		Level                string
		LearningStyle        string
		CompletionPercentage int
		StreakDays           int
		PreferredLanguage    string
	}
	Lesson struct {
		Topic      string
		Difficulty string
	}
}

func (input *LessonIntroduction) isStudentZero() bool {
	return input.Student.Name == "" &&
		input.Student.Level == "" &&
		input.Student.LearningStyle == "" &&
		input.Student.CompletionPercentage == 0 &&
		input.Student.StreakDays == 0 &&
		input.Student.PreferredLanguage == ""
}

func (input *LessonIntroduction) isLessonZero() bool {
	return input.Lesson.Topic == "" &&
		input.Lesson.Difficulty == ""
}

func (input *LessonIntroduction) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Student.CompletionPercentage)
	var1 := strconv.Itoa(input.Student.StreakDays)
	length := 0
	length += 7
	length += len(input.Subject)
	length += 22
	length += len(input.Student.Name)
	length += 92
	length += len(input.Student.Level)
	length += 23
	length += len(input.Student.LearningStyle)
	length += 17
	length += len(var0)
	length += 25
	length += len(var1)
	length += 12
	if input.Student.PreferredLanguage != "" {
		length += 31
		length += len(input.Student.PreferredLanguage)
		length += 2
	}
	length += 39
	length += len(input.Lesson.Topic)
	length += 17
	length += len(input.Lesson.Difficulty)
	length += 8
	if input.Student.Level == "beginner" {
		length += 100
	}
	length += 2
	if input.Student.Level == "intermediate" {
		length += 105
	}
	length += 2
	if input.Student.Level == "advanced" {
		length += 87
	}
	b.Grow(length)
	b.WriteString("# 📚 ")
	b.WriteString(input.Subject)
	b.WriteString(" Learning Session\n\nHi ")
	b.WriteString(input.Student.Name)
	b.WriteString("! Welcome to your personalized learning session.\n\n## 👤 Your Profile\n- **Current Level**: ")
	b.WriteString(input.Student.Level)
	b.WriteString("\n- **Learning Style**: ")
	b.WriteString(input.Student.LearningStyle)
	b.WriteString("\n- **Progress**: ")
	b.WriteString(var0)
	b.WriteString("% complete\n- **Streak**: ")
	b.WriteString(var1)
	b.WriteString(" days 🔥\n\n")
	if input.Student.PreferredLanguage != "" {
		b.WriteString("\n*Lesson will be delivered in: ")
		b.WriteString(input.Student.PreferredLanguage)
		b.WriteString("*\n")
	}
	b.WriteString("\n\n## 🎯 Today's Objective\n**Topic**: ")
	b.WriteString(input.Lesson.Topic)
	b.WriteString("\n**Difficulty**: ")
	b.WriteString(input.Lesson.Difficulty)
	b.WriteString("/5 ⭐\n\n")
	if input.Student.Level == "beginner" {
		b.WriteString("\nDon't worry if this seems challenging - we'll break everything down into simple, manageable steps!\n")
	}
	b.WriteString("\n\n")
	if input.Student.Level == "intermediate" {
		b.WriteString("\nYou're making great progress! Today we'll build on what you already know and explore some new concepts.\n")
	}
	b.WriteString("\n\n")
	if input.Student.Level == "advanced" {
		b.WriteString("\nReady for a challenge? Today's lesson will push your understanding to the next level.\n")
	}
	return b.String()
}

type AdaptiveContentDelivery struct {
	Lesson struct {
		HasPrerequisites     bool
		Prerequisites        string
		ReviewContent        string
		VisualContent        string
		HasDiagrams          bool
		Diagrams             string
		HasCharts            bool
		Charts               string
		AuditoryContent      string
		InteractiveExercises string
		PracticeActivities   string
		ConceptCount         int
	}
	Student struct {
		PrerequisitesScore int
		LearningStyle      string
		Level              string
	}
	Concepts struct {
		Concept1 string
		Concept2 string
		Concept3 string
		Concept4 string
		Concept5 string
	}
	Examples struct {
		Basic                 string
		BasicExplanation      string
		Intermediate          string
		IntermediateAnalysis  string
		IntermediateReasoning string
		Advanced              string
		AdvancedAnalysis      string
		Optimizations         string
	}
}

func (input *AdaptiveContentDelivery) isLessonZero() bool {
	return !input.Lesson.HasPrerequisites &&
		input.Lesson.Prerequisites == "" &&
		input.Lesson.ReviewContent == "" &&
		input.Lesson.VisualContent == "" &&
		!input.Lesson.HasDiagrams &&
		input.Lesson.Diagrams == "" &&
		!input.Lesson.HasCharts &&
		input.Lesson.Charts == "" &&
		input.Lesson.AuditoryContent == "" &&
		input.Lesson.InteractiveExercises == "" &&
		input.Lesson.PracticeActivities == "" &&
		input.Lesson.ConceptCount == 0
}

func (input *AdaptiveContentDelivery) isStudentZero() bool {
	return input.Student.PrerequisitesScore == 0 &&
		input.Student.LearningStyle == "" &&
		input.Student.Level == ""
}

func (input *AdaptiveContentDelivery) isConceptsZero() bool {
	return input.Concepts.Concept1 == "" &&
		input.Concepts.Concept2 == "" &&
		input.Concepts.Concept3 == "" &&
		input.Concepts.Concept4 == "" &&
		input.Concepts.Concept5 == ""
}

func (input *AdaptiveContentDelivery) isExamplesZero() bool {
	return input.Examples.Basic == "" &&
		input.Examples.BasicExplanation == "" &&
		input.Examples.Intermediate == "" &&
		input.Examples.IntermediateAnalysis == "" &&
		input.Examples.IntermediateReasoning == "" &&
		input.Examples.Advanced == "" &&
		input.Examples.AdvancedAnalysis == "" &&
		input.Examples.Optimizations == ""
}

func (input *AdaptiveContentDelivery) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Student.PrerequisitesScore)
	var1 := strconv.Itoa(input.Lesson.ConceptCount)
	length := 0
	if input.Lesson.HasPrerequisites {
		length += 94
		length += len(input.Lesson.Prerequisites)
		length += 2
		if input.Student.PrerequisitesScore != 0 {
			length += 30
			length += len(var0)
			length += 6
			if input.Student.PrerequisitesScore < 70 {
				length += 97
				length += len(input.Lesson.ReviewContent)
				length += 1
			}
			length += 2
			if input.Student.PrerequisitesScore >= 90 {
				length += 56
			}
			length += 1
		}
		length += 1
	}
	length += 26
	if input.Student.LearningStyle == "visual" {
		length += 35
		length += len(input.Lesson.VisualContent)
		length += 2
		if input.Lesson.HasDiagrams {
			length += 27
			length += len(input.Lesson.Diagrams)
			length += 1
		}
		length += 2
		if input.Lesson.HasCharts {
			length += 22
			length += len(input.Lesson.Charts)
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Student.LearningStyle == "auditory" {
		length += 37
		length += len(input.Lesson.AuditoryContent)
		length += 91
	}
	length += 2
	if input.Student.LearningStyle == "kinesthetic" {
		length += 100
		length += len(input.Lesson.InteractiveExercises)
		length += 27
		length += len(input.Lesson.PracticeActivities)
		length += 1
	}
	length += 25
	if input.Lesson.ConceptCount != 0 {
		length += 13
		length += len(var1)
		length += 26
		length += len(input.Concepts.Concept1)
		length += 4
		length += len(input.Concepts.Concept2)
		length += 1
		if input.Lesson.ConceptCount >= 3 {
			length += 4
			length += len(input.Concepts.Concept3)
			length += 1
		}
		length += 1
		if input.Lesson.ConceptCount >= 4 {
			length += 4
			length += len(input.Concepts.Concept4)
			length += 1
		}
		length += 1
		if input.Lesson.ConceptCount >= 5 {
			length += 4
			length += len(input.Concepts.Concept5)
			length += 1
		}
		length += 1
	}
	length += 20
	if input.Student.Level == "beginner" {
		length += 59
		length += len(input.Examples.Basic)
		length += 23
		length += len(input.Examples.BasicExplanation)
		length += 1
	}
	length += 2
	if input.Student.Level == "intermediate" {
		length += 58
		length += len(input.Examples.Intermediate)
		length += 20
		length += len(input.Examples.IntermediateAnalysis)
		length += 22
		length += len(input.Examples.IntermediateReasoning)
		length += 1
	}
	length += 2
	if input.Student.Level == "advanced" {
		length += 68
		length += len(input.Examples.Advanced)
		length += 21
		length += len(input.Examples.AdvancedAnalysis)
		length += 34
		length += len(input.Examples.Optimizations)
		length += 1
	}
	b.Grow(length)
	if input.Lesson.HasPrerequisites {
		b.WriteString("\n## 📋 Prerequisites Check\nBefore we start, let's make sure you understand these concepts:\n\n")
		b.WriteString(input.Lesson.Prerequisites)
		b.WriteString("\n\n")
		if input.Student.PrerequisitesScore != 0 {
			b.WriteString("\n**Your prerequisite score**: ")
			b.WriteString(var0)
			b.WriteString("/100\n\n")
			if input.Student.PrerequisitesScore < 70 {
				b.WriteString("\n🔄 **Recommendation**: Let's do a quick review of the basics first.\n\n### Quick Review Session\n")
				b.WriteString(input.Lesson.ReviewContent)
				b.WriteRune('\n')
			}
			b.WriteString("\n\n")
			if input.Student.PrerequisitesScore >= 90 {
				b.WriteString("\n✅ **Excellent!** You're ready for advanced concepts.\n")
			}
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🎓 Lesson Content\n\n")
	if input.Student.LearningStyle == "visual" {
		b.WriteString("\n### 📊 Visual Learning Approach\n")
		b.WriteString(input.Lesson.VisualContent)
		b.WriteString("\n\n")
		if input.Lesson.HasDiagrams {
			b.WriteString("\n**Interactive Diagrams:**\n")
			b.WriteString(input.Lesson.Diagrams)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Lesson.HasCharts {
			b.WriteString("\n**Charts & Graphs:**\n")
			b.WriteString(input.Lesson.Charts)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Student.LearningStyle == "auditory" {
		b.WriteString("\n### 🎵 Auditory Learning Approach\n")
		b.WriteString(input.Lesson.AuditoryContent)
		b.WriteString("\n\n*💡 Tip: Try reading this lesson out loud or use text-to-speech for better retention!*\n")
	}
	b.WriteString("\n\n")
	if input.Student.LearningStyle == "kinesthetic" {
		b.WriteString("\n### 🛠️ Hands-On Learning Approach\nLet's learn by doing! Here are some interactive exercises:\n\n")
		b.WriteString(input.Lesson.InteractiveExercises)
		b.WriteString("\n\n**Practice Activities:**\n")
		b.WriteString(input.Lesson.PracticeActivities)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🧠 Core Concepts\n\n")
	if input.Lesson.ConceptCount != 0 {
		b.WriteString("\nWe'll cover ")
		b.WriteString(var1)
		b.WriteString(" main concepts today:\n\n1. ")
		b.WriteString(input.Concepts.Concept1)
		b.WriteString("\n2. ")
		b.WriteString(input.Concepts.Concept2)
		b.WriteRune('\n')
		if input.Lesson.ConceptCount >= 3 {
			b.WriteString("\n3. ")
			b.WriteString(input.Concepts.Concept3)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
		if input.Lesson.ConceptCount >= 4 {
			b.WriteString("\n4. ")
			b.WriteString(input.Concepts.Concept4)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
		if input.Lesson.ConceptCount >= 5 {
			b.WriteString("\n5. ")
			b.WriteString(input.Concepts.Concept5)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 💡 Examples\n\n")
	if input.Student.Level == "beginner" {
		b.WriteString("\n### Simple Example\nLet's start with a basic example:\n\n```\n")
		b.WriteString(input.Examples.Basic)
		b.WriteString("\n```\n\n**Explanation**: ")
		b.WriteString(input.Examples.BasicExplanation)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Student.Level == "intermediate" {
		b.WriteString("\n### Practical Example\nHere's a real-world scenario:\n\n```\n")
		b.WriteString(input.Examples.Intermediate)
		b.WriteString("\n```\n\n**Analysis**: ")
		b.WriteString(input.Examples.IntermediateAnalysis)
		b.WriteString("\n\n**Why this works**: ")
		b.WriteString(input.Examples.IntermediateReasoning)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Student.Level == "advanced" {
		b.WriteString("\n### Complex Example\nLet's examine an advanced implementation:\n\n```\n")
		b.WriteString(input.Examples.Advanced)
		b.WriteString("\n```\n\n**Deep Dive**: ")
		b.WriteString(input.Examples.AdvancedAnalysis)
		b.WriteString("\n\n**Optimization Opportunities**: ")
		b.WriteString(input.Examples.Optimizations)
		b.WriteRune('\n')
	}
	return b.String()
}

type InteractiveAssessment struct {
	Assessment struct {
		HasQuiz    bool
		HasProject bool
	}
	Question struct {
		Number         int
		Text           string
		Type           string
		OptionA        string
		OptionB        string
		OptionC        string
		OptionD        string
		CodeTemplate   string
		ExpectedOutput string
		Prompt         string
		Hint           string
	}
	Project struct {
		Title            string
		EstimatedMinutes int
		Requirements     string
		Language         string
		StarterCode      string
		HasBonus         bool
		BonusChallenge   string
	}
}

func (input *InteractiveAssessment) isAssessmentZero() bool {
	return !input.Assessment.HasQuiz &&
		!input.Assessment.HasProject
}

func (input *InteractiveAssessment) isQuestionZero() bool {
	return input.Question.Number == 0 &&
		input.Question.Text == "" &&
		input.Question.Type == "" &&
		input.Question.OptionA == "" &&
		input.Question.OptionB == "" &&
		input.Question.OptionC == "" &&
		input.Question.OptionD == "" &&
		input.Question.CodeTemplate == "" &&
		input.Question.ExpectedOutput == "" &&
		input.Question.Prompt == "" &&
		input.Question.Hint == ""
}

func (input *InteractiveAssessment) isProjectZero() bool {
	return input.Project.Title == "" &&
		input.Project.EstimatedMinutes == 0 &&
		input.Project.Requirements == "" &&
		input.Project.Language == "" &&
		input.Project.StarterCode == "" &&
		!input.Project.HasBonus &&
		input.Project.BonusChallenge == ""
}

func (input *InteractiveAssessment) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Question.Number)
	var1 := strconv.Itoa(input.Project.EstimatedMinutes)
	length := 0
	length += 24
	if input.Assessment.HasQuiz {
		length += 39
		length += len(var0)
		length += 4
		length += len(input.Question.Text)
		length += 2
		if input.Question.Type == "multiple_choice" {
			length += 4
			length += len(input.Question.OptionA)
			length += 4
			length += len(input.Question.OptionB)
			length += 4
			length += len(input.Question.OptionC)
			length += 4
			length += len(input.Question.OptionD)
			length += 1
		}
		length += 2
		if input.Question.Type == "coding" {
			length += 27
			length += len(input.Question.CodeTemplate)
			length += 27
			length += len(input.Question.ExpectedOutput)
			length += 1
		}
		length += 2
		if input.Question.Type == "explanation" {
			length += 32
			length += len(input.Question.Prompt)
			length += 22
			length += len(input.Question.Hint)
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Assessment.HasProject {
		length += 36
		length += len(input.Project.Title)
		length += 21
		length += len(var1)
		length += 28
		length += len(input.Project.Requirements)
		length += 23
		length += len(input.Project.Language)
		length += 1
		length += len(input.Project.StarterCode)
		length += 6
		if input.Project.HasBonus {
			length += 22
			length += len(input.Project.BonusChallenge)
			length += 1
		}
		length += 1
	}
	b.Grow(length)
	b.WriteString("## 🎯 Practice Time!\n\n")
	if input.Assessment.HasQuiz {
		b.WriteString("\n### Quick Knowledge Check\n\n**Question ")
		b.WriteString(var0)
		b.WriteString("**: ")
		b.WriteString(input.Question.Text)
		b.WriteString("\n\n")
		if input.Question.Type == "multiple_choice" {
			b.WriteString("\nA) ")
			b.WriteString(input.Question.OptionA)
			b.WriteString("\nB) ")
			b.WriteString(input.Question.OptionB)
			b.WriteString("\nC) ")
			b.WriteString(input.Question.OptionC)
			b.WriteString("\nD) ")
			b.WriteString(input.Question.OptionD)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Question.Type == "coding" {
			b.WriteString("\n**Coding Challenge:**\n```\n")
			b.WriteString(input.Question.CodeTemplate)
			b.WriteString("\n```\n\n**Expected Output**: ")
			b.WriteString(input.Question.ExpectedOutput)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Question.Type == "explanation" {
			b.WriteString("\n**Explain in your own words**: ")
			b.WriteString(input.Question.Prompt)
			b.WriteString("\n\n*Hint*: Think about ")
			b.WriteString(input.Question.Hint)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Assessment.HasProject {
		b.WriteString("\n## 🚀 Mini Project\n\n**Project**: ")
		b.WriteString(input.Project.Title)
		b.WriteString("\n**Estimated Time**: ")
		b.WriteString(var1)
		b.WriteString(" minutes\n\n**Requirements**:\n")
		b.WriteString(input.Project.Requirements)
		b.WriteString("\n\n**Starter Code**:\n```")
		b.WriteString(input.Project.Language)
		b.WriteRune('\n')
		b.WriteString(input.Project.StarterCode)
		b.WriteString("\n```\n\n")
		if input.Project.HasBonus {
			b.WriteString("\n**Bonus Challenge**: ")
			b.WriteString(input.Project.BonusChallenge)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	return b.String()
}

type ProgressTracking struct {
	Progress struct {
		CurrentLesson   int
		TotalLessons    int
		StrugglingAreas string
		StrengthAreas   string
	}
	Student struct {
		CompletionPercentage int
		StreakDays           int
		Name                 string
	}
	NextSteps struct {
		FinalAssessment string
		NextTopic       string
		StudyMinutes    int
		HasHomework     bool
		Homework        string
	}
	Session struct {
		Timestamp string
	}
}

func (input *ProgressTracking) isProgressZero() bool {
	return input.Progress.CurrentLesson == 0 &&
		input.Progress.TotalLessons == 0 &&
		input.Progress.StrugglingAreas == "" &&
		input.Progress.StrengthAreas == ""
}

func (input *ProgressTracking) isStudentZero() bool {
	return input.Student.CompletionPercentage == 0 &&
		input.Student.StreakDays == 0 &&
		input.Student.Name == ""
}

func (input *ProgressTracking) isNextStepsZero() bool {
	return input.NextSteps.FinalAssessment == "" &&
		input.NextSteps.NextTopic == "" &&
		input.NextSteps.StudyMinutes == 0 &&
		!input.NextSteps.HasHomework &&
		input.NextSteps.Homework == ""
}

func (input *ProgressTracking) isSessionZero() bool {
	return input.Session.Timestamp == ""
}

func (input *ProgressTracking) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Progress.CurrentLesson)
	var1 := strconv.Itoa(input.Progress.TotalLessons)
	var2 := strconv.Itoa(input.Student.StreakDays)
	var3 := strconv.Itoa(input.NextSteps.StudyMinutes)
	length := 0
	length += 46
	length += len(var0)
	length += 1
	length += len(var1)
	length += 31
	length += len(strconv.Itoa(input.Student.CompletionPercentage))
	length += 3
	if input.Student.StreakDays >= 7 {
		length += 31
		length += len(var2)
		length += 23
		if input.Student.StreakDays >= 30 {
			length += 66
		}
		length += 2
		if input.Progress.StrugglingAreas != "" {
			length += 74
			length += len(input.Progress.StrugglingAreas)
			length += 1
		}
		length += 2
		if input.Progress.StrengthAreas != "" {
			length += 46
			length += len(input.Progress.StrengthAreas)
			length += 1
		}
		length += 22
		if input.Student.CompletionPercentage >= 80 {
			length += 74
			length += len(input.NextSteps.FinalAssessment)
			length += 1
		}
		length += 2
		if input.Student.CompletionPercentage < 80 {
			length += 18
			length += len(input.NextSteps.NextTopic)
			length += 29
			length += len(var3)
			length += 10
			if input.NextSteps.HasHomework {
				length += 26
				length += len(input.NextSteps.Homework)
				length += 1
			}
			length += 1
		}
		length += 31
		length += len(input.Student.Name)
		length += 31
		length += len(input.Session.Timestamp)
		length += 2
	}
	b.Grow(length)
	b.WriteString("## 📈 Your Progress\n\n**Lesson Completion**: ")
	b.WriteString(var0)
	b.WriteString("/")
	b.WriteString(var1)
	b.WriteString(" lessons\n**Overall Progress**: ")
	b.WriteString(strconv.Itoa(input.Student.CompletionPercentage))
	b.WriteString("%\n\n")
	if input.Student.StreakDays >= 7 {
		b.WriteString("\n🎉 **Amazing!** You're on a ")
		b.WriteString(var2)
		b.WriteString("-day learning streak!\n\n")
		if input.Student.StreakDays >= 30 {
			b.WriteString("\n🏆 **Legendary Learner!** 30+ day streak - you're unstoppable!\n")
		}
		b.WriteString("\n\n")
		if input.Progress.StrugglingAreas != "" {
			b.WriteString("\n### 📝 Areas for Review\nBased on your performance, consider reviewing:\n")
			b.WriteString(input.Progress.StrugglingAreas)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Progress.StrengthAreas != "" {
			b.WriteString("\n### 💪 Your Strengths\nYou're excelling in:\n")
			b.WriteString(input.Progress.StrengthAreas)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n## 🎯 Next Steps\n\n")
		if input.Student.CompletionPercentage >= 80 {
			b.WriteString("\n🎓 **Almost there!** You're ready for the final assessment.\n\n**Next**: ")
			b.WriteString(input.NextSteps.FinalAssessment)
			b.WriteRune('\n')
		}
		b.WriteString("\n\n")
		if input.Student.CompletionPercentage < 80 {
			b.WriteString("\n**Next Lesson**: ")
			b.WriteString(input.NextSteps.NextTopic)
			b.WriteString("\n**Recommended Study Time**: ")
			b.WriteString(var3)
			b.WriteString(" minutes\n\n")
			if input.NextSteps.HasHomework {
				b.WriteString("\n**Homework Assignment**: ")
				b.WriteString(input.NextSteps.Homework)
				b.WriteRune('\n')
			}
			b.WriteRune('\n')
		}
		b.WriteString("\n\n---\n*Keep up the great work, ")
		b.WriteString(input.Student.Name)
		b.WriteString("! 🌟*\n*Session completed at: ")
		b.WriteString(input.Session.Timestamp)
		b.WriteString("* ")
	}
	return b.String()
}
