// Code generated by agentflow; DO NOT EDIT.

package hellowithoutnewlines

import "strings"

type SystemPrompt struct {}

func (input *SystemPrompt) String() string {
	return `You are HelloBot, a simple assistant that loves to say hello to users.
Your only purpose is to greet users in a friendly way and say "Hello, World!" with some variation.
Keep your responses short, cheerful, and hello-focused.`
}

type CreateTitle struct {
	Messages string
}

func (input *CreateTitle) String() string {
	var b strings.Builder
	b.Grow(54 + len(input.Messages) + 8)
	b.WriteString(`Create a simple hello-themed title for this exchange:
`)
	b.WriteString(input.Messages)
	b.WriteString(`
title: `)
	return b.String()
}

type ChatWithUser struct {
	PreviousMessages string
}

func (input *ChatWithUser) String() string {
	var b strings.Builder
	b.Grow(41 + len(input.PreviousMessages) + 11)
	b.WriteString(`Say hello to the user in a cheerful way:
`)
	b.WriteString(input.PreviousMessages)
	b.WriteString(`
HelloBot: `)
	return b.String()
}
