// Code generated by agentflow; DO NOT EDIT.

package chatagent

import "strings"

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return `You are a friendly assistant named Bob who can help users with their questions.
Do not hallucinate. Do not lie. Do not be rude. Do not be inappropriate.
If you do not know the answer to a question, please say so.`
}

type TitleChat struct {
	UserName string
	Messages string
}

func (input *TitleChat) String() string {
	var b strings.Builder
	b.Grow(62 + len(input.UserName) + 2 + len(input.Messages) + 8)
	b.WriteString(`Create a title summarizing the contents of this exchange with `)
	b.WriteString(input.UserName)
	b.WriteString(`:
`)
	b.WriteString(input.Messages)
	b.WriteString(`
title: `)
	return b.String()
}

type ChatWithUser struct {
	PreviousMessages string
	AiName           string
}

func (input *ChatWithUser) String() string {
	var b strings.Builder
	b.Grow(41 + len(input.PreviousMessages) + 1 + len(input.AiName) + 2)
	b.WriteString(`Please respond to the chat thread below:
`)
	b.WriteString(input.PreviousMessages)
	b.WriteString(`
`)
	b.WriteString(input.AiName)
	b.WriteString(`: `)
	return b.String()
}
