// Code generated by agentflow v0.3.0; DO NOT EDIT.

package chatagent

import (
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return `You are a friendly assistant named Bob who can help users with their questions.
Do not hallucinate. Do not lie. Do not be rude. Do not be inappropriate.
If you do not know the answer to a question, please say so.`
}

type TitleChat struct {
	UserName string
	Messages string
}

func (input *TitleChat) String() string {
	var b strings.Builder
	length := 0
	length += 62
	length += len(input.UserName)
	length += 2
	length += len(input.Messages)
	length += 8
	b.Grow(length)
	b.WriteString(`Create a title summarizing the contents of this exchange with `)
	b.WriteString(input.UserName)
	b.WriteString(`:
`)
	b.WriteString(input.Messages)
	b.WriteString(`
title: `)
	return b.String()
}

type ChatWithUser struct {
	PreviousMessages string
	AiName           string
}

func (input *ChatWithUser) String() string {
	var b strings.Builder
	length := 0
	length += 41
	length += len(input.PreviousMessages)
	length += 1
	length += len(input.AiName)
	length += 2
	b.Grow(length)
	b.WriteString(`Please respond to the chat thread below:
`)
	b.WriteString(input.PreviousMessages)
	b.WriteRune('\n')
	b.WriteString(input.AiName)
	b.WriteString(`: `)
	return b.String()
}
