// Code generated by agentflow v0.4.2; DO NOT EDIT.

package simplest

import (
	"strings"
)

type ApiDocumentationGenerator struct{}

func (input *ApiDocumentationGenerator) String() string {
	return "You are APIDocBot, an intelligent documentation generator that creates comprehensive, up-to-date API documentation with interactive examples, versioning support, and developer-friendly formatting."
}

type ApiOverview struct {
	Api struct {
		Name     string
		BaseUrl  string
		Protocol string
		AuthType string
	}
}

func (input *ApiOverview) isApiZero() bool {
	return input.Api.Name == "" &&
		input.Api.BaseUrl == "" &&
		input.Api.Protocol == "" &&
		input.Api.AuthType == ""
}

func (input *ApiOverview) String() string {
	var b strings.Builder
	length := 0
	length += 7
	length += len(input.Api.Name)
	length += 35
	length += len(input.Api.BaseUrl)
	length += 16
	length += len(input.Api.Protocol)
	length += 21
	length += len(input.Api.AuthType)
	b.Grow(length)
	b.WriteString("# 📡 ")
	b.WriteString(input.Api.Name)
	b.WriteString(" API Documentation\n\n**Base URL**: `")
	b.WriteString(input.Api.BaseUrl)
	b.WriteString("`\n**Protocol**: ")
	b.WriteString(input.Api.Protocol)
	b.WriteString("\n**Authentication**: ")
	b.WriteString(input.Api.AuthType)
	return b.String()
}
