// Code generated by agentflow v0.5.3; DO NOT EDIT.

package simpleapidocs

import (
	"strconv"
	"strings"
)

type ApiDocumentationGenerator struct{}

func (input *ApiDocumentationGenerator) String() string {
	return "You are APIDocBot, an intelligent documentation generator that creates comprehensive, up-to-date API documentation with interactive examples, versioning support, and developer-friendly formatting."
}

type ApiOverview struct {
	Api struct {
		Name               string
		Version            string
		BaseUrl            string
		Protocol           string
		AuthType           string
		Deprecated         bool
		ReplacementVersion string
		SunsetDate         string
		Beta               bool
		StabilityLevel     string
	}
	Changelog struct {
		HasBreakingChanges bool
		BreakingChanges    string
		NewFeatures        string
		Improvements       string
		BugFixes           string
	}
	Docs struct {
		MigrationUrl string
	}
	Auth struct {
		Type         string
		Required     bool
		DashboardUrl string
		OauthFlow    string
		Scopes       string
		AuthUrl      string
		TokenUrl     string
		HasScopes    bool
		ScopeList    string
		HeaderName   string
		QueryParam   string
		RateLimits   bool
	}
	RateLimits struct {
		StandardRequests int
		StandardWindow   string
		PremiumRequests  int
		PremiumWindow    string
		HasBurst         bool
		BurstRequests    int
		BurstWindow      string
	}
}

func (input *ApiOverview) isApiZero() bool {
	return input.Api.Name == "" &&
		input.Api.Version == "" &&
		input.Api.BaseUrl == "" &&
		input.Api.Protocol == "" &&
		input.Api.AuthType == "" &&
		!input.Api.Deprecated &&
		input.Api.ReplacementVersion == "" &&
		input.Api.SunsetDate == "" &&
		!input.Api.Beta &&
		input.Api.StabilityLevel == ""
}

func (input *ApiOverview) isChangelogZero() bool {
	return !input.Changelog.HasBreakingChanges &&
		input.Changelog.BreakingChanges == "" &&
		input.Changelog.NewFeatures == "" &&
		input.Changelog.Improvements == "" &&
		input.Changelog.BugFixes == ""
}

func (input *ApiOverview) isDocsZero() bool {
	return input.Docs.MigrationUrl == ""
}

func (input *ApiOverview) isAuthZero() bool {
	return input.Auth.Type == "" &&
		!input.Auth.Required &&
		input.Auth.DashboardUrl == "" &&
		input.Auth.OauthFlow == "" &&
		input.Auth.Scopes == "" &&
		input.Auth.AuthUrl == "" &&
		input.Auth.TokenUrl == "" &&
		!input.Auth.HasScopes &&
		input.Auth.ScopeList == "" &&
		input.Auth.HeaderName == "" &&
		input.Auth.QueryParam == "" &&
		!input.Auth.RateLimits
}

func (input *ApiOverview) isRateLimitsZero() bool {
	return input.RateLimits.StandardRequests == 0 &&
		input.RateLimits.StandardWindow == "" &&
		input.RateLimits.PremiumRequests == 0 &&
		input.RateLimits.PremiumWindow == "" &&
		!input.RateLimits.HasBurst &&
		input.RateLimits.BurstRequests == 0 &&
		input.RateLimits.BurstWindow == ""
}

func (input *ApiOverview) String() string {
	var b strings.Builder
	var0 := strconv.FormatBool(input.Auth.Required)
	var1 := strconv.FormatBool(input.Auth.HasScopes)
	var2 := strconv.Itoa(input.RateLimits.StandardRequests)
	var3 := strconv.Itoa(input.RateLimits.PremiumRequests)
	var4 := strconv.Itoa(input.RateLimits.BurstRequests)
	length := 0
	length += 7
	length += len(input.Api.Name)
	length += 33
	length += len(input.Api.Version)
	length += 16
	length += len(input.Api.BaseUrl)
	length += 16
	length += len(input.Api.Protocol)
	length += 21
	length += len(input.Api.AuthType)
	length += 2
	if input.Api.Deprecated {
		length += 86
		length += len(input.Api.ReplacementVersion)
		length += 19
		length += len(input.Api.SunsetDate)
		length += 1
	}
	length += 2
	if input.Api.Beta {
		length += 92
		length += len(input.Api.StabilityLevel)
		length += 3
	}
	length += 25
	length += len(input.Api.Version)
	length += 2
	if input.Changelog.HasBreakingChanges {
		length += 27
		length += len(input.Changelog.BreakingChanges)
		length += 59
		length += len(input.Docs.MigrationUrl)
		length += 28
	}
	length += 2
	if input.Changelog.NewFeatures != "" {
		length += 22
		length += len(input.Changelog.NewFeatures)
		length += 1
	}
	length += 2
	if input.Changelog.Improvements != "" {
		length += 23
		length += len(input.Changelog.Improvements)
		length += 1
	}
	length += 2
	if input.Changelog.BugFixes != "" {
		length += 20
		length += len(input.Changelog.BugFixes)
		length += 1
	}
	length += 36
	length += len(input.Auth.Type)
	length += 15
	length += len(var0)
	length += 2
	if input.Auth.Type == "bearer" {
		length += 176
		length += len(input.Auth.DashboardUrl)
		length += 2
	}
	length += 2
	if input.Auth.Type == "oauth2" {
		length += 40
		length += len(input.Auth.OauthFlow)
		length += 13
		length += len(input.Auth.Scopes)
		length += 26
		length += len(input.Auth.AuthUrl)
		length += 18
		length += len(input.Auth.TokenUrl)
		length += 3
		if input.Auth.HasScopes {
			length += 23
			length += len(input.Auth.ScopeList)
			length += 1
		} else {
			length += 13
			length += len(var1)
			length += 1
		}
		length += 1
	}
	length += 2
	if input.Auth.Type == "apikey" {
		length += 41
		length += len(input.Auth.HeaderName)
		length += 24
		length += len(input.Auth.QueryParam)
		length += 25
		length += len(input.Auth.HeaderName)
		length += 19
	}
	length += 2
	if input.Auth.RateLimits {
		length += 41
		length += len(var2)
		length += 10
		length += len(input.RateLimits.StandardWindow)
		length += 19
		length += len(var3)
		length += 10
		length += len(input.RateLimits.PremiumWindow)
		length += 165
		if input.RateLimits.HasBurst {
			length += 22
			length += len(var4)
			length += 13
			length += len(input.RateLimits.BurstWindow)
			length += 9
		}
		length += 1
	}
	length += 1
	b.Grow(length)
	b.WriteString("# 📡 ")
	b.WriteString(input.Api.Name)
	b.WriteString(" API Documentation\n\n**Version**: ")
	b.WriteString(input.Api.Version)
	b.WriteString("\n**Base URL**: `")
	b.WriteString(input.Api.BaseUrl)
	b.WriteString("`\n**Protocol**: ")
	b.WriteString(input.Api.Protocol)
	b.WriteString("\n**Authentication**: ")
	b.WriteString(input.Api.AuthType)
	b.WriteString("\n\n")
	if input.Api.Deprecated {
		b.WriteString("\n⚠️ **DEPRECATED API**: This API version is deprecated. Please migrate to version ")
		b.WriteString(input.Api.ReplacementVersion)
		b.WriteString(".\n**Sunset Date**: ")
		b.WriteString(input.Api.SunsetDate)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Api.Beta {
		b.WriteString("\n🧪 **BETA API**: This API is in beta. Features may change without notice.\n**Stability**: ")
		b.WriteString(input.Api.StabilityLevel)
		b.WriteString("/5\n")
	}
	b.WriteString("\n\n## 🌟 What's New in v")
	b.WriteString(input.Api.Version)
	b.WriteString("\n\n")
	if input.Changelog.HasBreakingChanges {
		b.WriteString("\n### 💥 Breaking Changes\n")
		b.WriteString(input.Changelog.BreakingChanges)
		b.WriteString("\n\n⚠️ **Migration Required**: See our [migration guide](")
		b.WriteString(input.Docs.MigrationUrl)
		b.WriteString(") for upgrade instructions.\n")
	}
	b.WriteString("\n\n")
	if input.Changelog.NewFeatures != "" {
		b.WriteString("\n### ✨ New Features\n")
		b.WriteString(input.Changelog.NewFeatures)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Changelog.Improvements != "" {
		b.WriteString("\n### 🚀 Improvements\n")
		b.WriteString(input.Changelog.Improvements)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Changelog.BugFixes != "" {
		b.WriteString("\n### 🐛 Bug Fixes\n")
		b.WriteString(input.Changelog.BugFixes)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n## 🔐 Authentication\n\n**Type**: ")
	b.WriteString(input.Auth.Type)
	b.WriteString("\n**Required**: ")
	b.WriteString(var0)
	b.WriteString("\n\n")
	if input.Auth.Type == "bearer" {
		b.WriteString("\n### Bearer Token Authentication\nInclude your API key in the Authorization header:\n\n```http\nAuthorization: Bearer YOUR_API_KEY\n```\n\n**Get your API key**: [Developer Dashboard](")
		b.WriteString(input.Auth.DashboardUrl)
		b.WriteString(")\n")
	}
	b.WriteString("\n\n")
	if input.Auth.Type == "oauth2" {
		b.WriteString("\n### OAuth 2.0 Authentication\n**Flow**: ")
		b.WriteString(input.Auth.OauthFlow)
		b.WriteString("\n**Scopes**: ")
		b.WriteString(input.Auth.Scopes)
		b.WriteString("\n\n**Authorization URL**: `")
		b.WriteString(input.Auth.AuthUrl)
		b.WriteString("`\n**Token URL**: `")
		b.WriteString(input.Auth.TokenUrl)
		b.WriteString("`\n\n")
		if input.Auth.HasScopes {
			b.WriteString("\n#### Required Scopes:\n")
			b.WriteString(input.Auth.ScopeList)
			b.WriteRune('\n')
		} else {
			b.WriteString("\nHas Scopes: ")
			b.WriteString(var1)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Auth.Type == "apikey" {
		b.WriteString("\n### API Key Authentication\n**Header**: `")
		b.WriteString(input.Auth.HeaderName)
		b.WriteString("`\n**Query Parameter**: `")
		b.WriteString(input.Auth.QueryParam)
		b.WriteString("` (alternative)\n\n```http\n")
		b.WriteString(input.Auth.HeaderName)
		b.WriteString(": YOUR_API_KEY\n```\n")
	}
	b.WriteString("\n\n")
	if input.Auth.RateLimits {
		b.WriteString("\n## 📊 Rate Limits\n\n**Standard Tier**: ")
		b.WriteString(var2)
		b.WriteString(" requests/")
		b.WriteString(input.RateLimits.StandardWindow)
		b.WriteString("\n**Premium Tier**: ")
		b.WriteString(var3)
		b.WriteString(" requests/")
		b.WriteString(input.RateLimits.PremiumWindow)
		b.WriteString("\n\n**Rate Limit Headers**:\n- `X-RateLimit-Limit`: Total requests allowed\n- `X-RateLimit-Remaining`: Requests remaining\n- `X-RateLimit-Reset`: Time when limit resets\n\n")
		if input.RateLimits.HasBurst {
			b.WriteString("\n**Burst Allowance**: ")
			b.WriteString(var4)
			b.WriteString(" requests in ")
			b.WriteString(input.RateLimits.BurstWindow)
			b.WriteString(" seconds\n")
		}
		b.WriteRune('\n')
	}
	b.WriteRune('\n')
	return b.String()
}
